// Generated by RSD - Do not modify
package at.mspe.server.service.model.mixins;

import at.mspe.server.service.model.Gender;

public interface CohortBaseMixin {
	public String name();

	public Gender gender();

}
