// Generated by RSD - Do not modify
package at.mspe.server.service.model.mixins;

import java.time.LocalDate;

public interface ParticipantBaseMixin {
	public String firstname();

	public String lastname();

	public String team();

	public LocalDate birthday();

}
