// Generated by RSD - Do not modify
package at.mspe.server.service.model.mixins;

import java.time.ZonedDateTime;

public interface SportEventBaseMixin {
	public String name();

	public ZonedDateTime date();

}
