// Generated by RSD - Do not modify
package at.mspe.server.service.model;

import java.util.Optional;
import java.util.OptionalInt;

import at.mspe.server.service.model.mixins.BirthyearCohortBaseMixin;
import at.mspe.server.service.model.mixins.CohortBaseMixin;

public interface BirthyearCohort {

	public interface Data extends _Base.BaseData, BirthyearCohort, CohortBaseMixin, BirthyearCohortBaseMixin, Cohort.Data {
		public String key();

		public long version();

		public String name();

		public int min();

		public int max();

	}

	public interface DataBuilder extends _Base.BaseDataBuilder<BirthyearCohort.Data>, Cohort.DataBuilder {
		public DataBuilder key(String key);

		public DataBuilder version(long version);

		public DataBuilder name(String name);

		public DataBuilder min(int min);

		public DataBuilder max(int max);

	}

	public interface Patch extends _Base.BaseData, BirthyearCohort, Cohort.Patch {
		public String key();

		public long version();

		public Optional<String> name();

		public OptionalInt min();

		public OptionalInt max();

	}

	public interface PatchBuilder extends _Base.BaseDataBuilder<BirthyearCohort.Patch>, Cohort.PatchBuilder {
		public PatchBuilder key(String key);

		public PatchBuilder version(long version);

		public PatchBuilder name(String name);

		public PatchBuilder min(int min);

		public PatchBuilder max(int max);

	}
}
