// Generated by RSD - Do not modify
package at.mspe.server.service.model;

import at.mspe.server.service.model.mixins.BirthyearCohortBaseMixin;
import at.mspe.server.service.model.mixins.CohortBaseMixin;

public interface BirthyearCohortNew {

	public interface Data extends _Base.BaseData, BirthyearCohortNew, CohortBaseMixin, BirthyearCohortBaseMixin, CohortNew.Data {
		public String name();

		public Gender gender();

		public int min();

		public int max();

	}

	public interface DataBuilder extends _Base.BaseDataBuilder<BirthyearCohortNew.Data>, CohortNew.DataBuilder {
		public DataBuilder name(String name);

		public DataBuilder gender(Gender gender);

		public DataBuilder min(int min);

		public DataBuilder max(int max);

	}
}
