// Generated by RSD - Do not modify
package at.mspe.server.service.model;

import at.mspe.server.service.model.mixins.BirthyearCohortBaseMixin;
import at.mspe.server.service.model.mixins.CohortBaseMixin;

public interface BirthyearCohortNew {

	public interface Data extends _Base.BaseData, BirthyearCohortNew, CohortBaseMixin, BirthyearCohortBaseMixin, CohortNew.Data {
		@Override
		public String name();

		@Override
		public Gender gender();

		@Override
		public boolean autoAssign();

		@Override
		public int min();

		@Override
		public int max();

	}

	public interface DataBuilder extends _Base.BaseDataBuilder<BirthyearCohortNew.Data>, CohortNew.DataBuilder {
		public DataBuilder name(String name);

		public DataBuilder gender(Gender gender);

		public DataBuilder autoAssign(boolean autoAssign);

		public DataBuilder min(int min);

		public DataBuilder max(int max);

	}
}
