// Generated by RSD - Do not modify
package at.mspe.server.service.model;

import java.util.List;

public interface CheckCsvResult {

	public interface Data extends _Base.BaseData, CheckCsvResult {
		public List<CheckCsvResultParticipant.Data> unkownParticipants();

		public List<CheckCsvResultParticipant.Data> noTimeParticipants();

	}

	public interface DataBuilder extends _Base.BaseDataBuilder<CheckCsvResult.Data> {
		public DataBuilder unkownParticipants(List<CheckCsvResultParticipant.Data> unkownParticipants);

		public DataBuilder noTimeParticipants(List<CheckCsvResultParticipant.Data> noTimeParticipants);

	}
}
