// Generated by RSD - Do not modify
package at.mspe.server.service.model;

public interface CheckCsvResultParticipant {

	public interface Data extends _Base.BaseData, CheckCsvResultParticipant {
		public String key();

		public String firstname();

		public String lastname();

	}

	public interface DataBuilder extends _Base.BaseDataBuilder<CheckCsvResultParticipant.Data> {
		public DataBuilder key(String key);

		public DataBuilder firstname(String firstname);

		public DataBuilder lastname(String lastname);

	}
}
