// Generated by RSD - Do not modify
package at.mspe.server.service.model;

public interface CohortNew {
	public interface Builder {

	}

	public interface Data extends _Base.BaseData, CohortNew {
		public String name();

	}

	public interface DataBuilder extends Builder {
	}
}
