// Generated by RSD - Do not modify
package at.mspe.server.service.model;

import java.util.Optional;

public interface Cohort {
	public interface Builder {

	}

	public interface Data extends _Base.BaseData, Cohort {
		public String key();

		public long version();

		public String name();

		public Gender gender();

	}

	public interface DataBuilder extends Builder {
	}

	public interface Patch extends _Base.BaseData, Cohort {
		public String key();

		public long version();

		public Optional<String> name();

		public Optional<Gender> gender();

	}

	public interface PatchBuilder extends Builder {
	}

}
