// Generated by RSD - Do not modify
package at.mspe.server.service.model;

import at.mspe.server.service.model.mixins.CohortBaseMixin;

public interface GenericCohortNew {

	public interface Data extends _Base.BaseData, GenericCohortNew, CohortBaseMixin, CohortNew.Data {
		@Override
		public String name();

		@Override
		public Gender gender();

		@Override
		public boolean autoAssign();

	}

	public interface DataBuilder extends _Base.BaseDataBuilder<GenericCohortNew.Data>, CohortNew.DataBuilder {
		public DataBuilder name(String name);

		public DataBuilder gender(Gender gender);

		public DataBuilder autoAssign(boolean autoAssign);

	}
}
