// Generated by RSD - Do not modify
package at.mspe.server.service.model;

import java.util.Optional;

import at.mspe.server.service.model.mixins.CohortBaseMixin;

public interface GenericCohort {

	public interface Data extends _Base.BaseData, GenericCohort, CohortBaseMixin, Cohort.Data {
		public String key();

		public long version();

		public int participantCount();

		@Override
		public String name();

		@Override
		public Gender gender();

		@Override
		public boolean autoAssign();

	}

	public interface DataBuilder extends _Base.BaseDataBuilder<GenericCohort.Data>, Cohort.DataBuilder {
		public DataBuilder key(String key);

		public DataBuilder version(long version);

		public DataBuilder participantCount(int participantCount);

		public DataBuilder name(String name);

		public DataBuilder gender(Gender gender);

		public DataBuilder autoAssign(boolean autoAssign);

	}

	public interface Patch extends _Base.BaseData, GenericCohort, Cohort.Patch {
		public String key();

		public long version();

		public Optional<String> name();

		public Optional<Gender> gender();

		public Optional<Boolean> autoAssign();

	}

	public interface PatchBuilder extends _Base.BaseDataBuilder<GenericCohort.Patch>, Cohort.PatchBuilder {
		public PatchBuilder key(String key);

		public PatchBuilder version(long version);

		public PatchBuilder name(String name);

		public PatchBuilder gender(Gender gender);

		public PatchBuilder autoAssign(boolean autoAssign);

	}
}
