// Generated by RSD - Do not modify
package at.mspe.server.service.model;

import at.mspe.server.service.model.mixins.CohortBaseMixin;

public interface GenericCohortNew {

	public interface Data extends _Base.BaseData, GenericCohortNew, CohortBaseMixin, CohortNew.Data {
		public String name();

	}

	public interface DataBuilder extends _Base.BaseDataBuilder<GenericCohortNew.Data>, CohortNew.DataBuilder {
		public DataBuilder name(String name);

	}
}
