// Generated by RSD - Do not modify
package at.mspe.server.service.model;

import java.util.Optional;

import at.mspe.server.service.model.mixins.CohortBaseMixin;

public interface GenericCohort {

	public interface Data extends _Base.BaseData, GenericCohort, CohortBaseMixin, Cohort.Data {
		public String key();

		public String name();

	}

	public interface DataBuilder extends _Base.BaseDataBuilder<GenericCohort.Data>, Cohort.DataBuilder {
		public DataBuilder key(String key);

		public DataBuilder name(String name);

	}

	public interface Patch extends _Base.BaseData, GenericCohort, Cohort.Patch {
		public String key();

		public Optional<String> name();

	}

	public interface PatchBuilder extends _Base.BaseDataBuilder<GenericCohort.Patch>, Cohort.PatchBuilder {
		public PatchBuilder key(String key);

		public PatchBuilder name(String name);

	}
}
