// Generated by RSD - Do not modify
package at.mspe.server.service.model;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

import at.mspe.server.service.model.mixins.ParticipantBaseMixin;

public interface Participant {

	public interface Data extends _Base.BaseData, Participant, ParticipantBaseMixin {
		public String key();

		public long version();

		public List<String> teamMates();

		public String firstname();

		public String lastname();

		public String team();

		public LocalDate birthday();

		public Gender gender();

		public String association();

	}

	public interface DataBuilder extends _Base.BaseDataBuilder<Participant.Data> {
		public DataBuilder key(String key);

		public DataBuilder version(long version);

		public DataBuilder teamMates(List<String> teamMates);

		public DataBuilder firstname(String firstname);

		public DataBuilder lastname(String lastname);

		public DataBuilder team(String team);

		public DataBuilder birthday(LocalDate birthday);

		public DataBuilder gender(Gender gender);

		public DataBuilder association(String association);

	}

	public interface Patch extends _Base.BaseData, Participant {
		public String key();

		public long version();

		public Optional<String> firstname();

		public Optional<String> lastname();

		public Optional<String> team();

		public Optional<LocalDate> birthday();

		public Optional<Gender> gender();

		public _Base.Nillable<String> association();

	}

	public interface PatchBuilder extends _Base.BaseDataBuilder<Participant.Patch> {
		public PatchBuilder key(String key);

		public PatchBuilder version(long version);

		public PatchBuilder firstname(String firstname);

		public PatchBuilder lastname(String lastname);

		public PatchBuilder team(String team);

		public PatchBuilder birthday(LocalDate birthday);

		public PatchBuilder gender(Gender gender);

		public PatchBuilder association(String association);

	}
}
