// Generated by RSD - Do not modify
package at.mspe.server.service.model;

import java.time.LocalDate;

import at.mspe.server.service.model.mixins.ParticipantBaseMixin;

public interface ParticipantNew {

	public interface Data extends _Base.BaseData, ParticipantNew, ParticipantBaseMixin {
		@Override
		public String firstname();

		@Override
		public String lastname();

		@Override
		public String team();

		@Override
		public LocalDate birthday();

		@Override
		public Gender gender();

		@Override
		public String association();

		@Override
		public String cohortKey();

		@Override
		public boolean publishName();

	}

	public interface DataBuilder extends _Base.BaseDataBuilder<ParticipantNew.Data> {
		public DataBuilder firstname(String firstname);

		public DataBuilder lastname(String lastname);

		public DataBuilder team(String team);

		public DataBuilder birthday(LocalDate birthday);

		public DataBuilder gender(Gender gender);

		public DataBuilder association(String association);

		public DataBuilder cohortKey(String cohortKey);

		public DataBuilder publishName(boolean publishName);

	}
}
