// Generated by RSD - Do not modify
package at.mspe.server.service.model;

import java.time.LocalDate;

import at.mspe.server.service.model.mixins.ParticipantBaseMixin;

public interface ParticipantNew {

	public interface Data extends _Base.BaseData, ParticipantNew, ParticipantBaseMixin {
		public String firstname();

		public String lastname();

		public String team();

		public LocalDate birthday();

	}

	public interface DataBuilder extends _Base.BaseDataBuilder<ParticipantNew.Data> {
		public DataBuilder firstname(String firstname);

		public DataBuilder lastname(String lastname);

		public DataBuilder team(String team);

		public DataBuilder birthday(LocalDate birthday);

	}
}
