// Generated by RSD - Do not modify
package at.mspe.server.service.model;

import java.time.ZonedDateTime;

import at.mspe.server.service.model.mixins.SportEventBaseMixin;

public interface SportEventNew {

	public interface Data extends _Base.BaseData, SportEventNew, SportEventBaseMixin {
		@Override
		public String name();

		@Override
		public ZonedDateTime date();

		@Override
		public String registrationUrl();

		@Override
		public Status status();

	}

	public interface DataBuilder extends _Base.BaseDataBuilder<SportEventNew.Data> {
		public DataBuilder name(String name);

		public DataBuilder date(ZonedDateTime date);

		public DataBuilder registrationUrl(String registrationUrl);

		public DataBuilder status(Status status);

	}
}
