// Generated by RSD - Do not modify
package at.mspe.server.service.model;

import java.time.ZonedDateTime;

import at.mspe.server.service.model.mixins.SportEventBaseMixin;

public interface SportEvent {

	public interface Data extends _Base.BaseData, SportEvent, SportEventBaseMixin {
		public String key();

		public String name();

		public ZonedDateTime date();

	}

	public interface DataBuilder extends _Base.BaseDataBuilder<SportEvent.Data> {
		public DataBuilder key(String key);

		public DataBuilder name(String name);

		public DataBuilder date(ZonedDateTime date);

	}
}
