// Generated by RSD - Do not modify
package at.mspe.server.service.model;

import java.time.ZonedDateTime;

import at.mspe.server.service.model.mixins.SportEventBaseMixin;

public interface SportEventNew {

	public interface Data extends _Base.BaseData, SportEventNew, SportEventBaseMixin {
		public String name();

		public ZonedDateTime date();

	}

	public interface DataBuilder extends _Base.BaseDataBuilder<SportEventNew.Data> {
		public DataBuilder name(String name);

		public DataBuilder date(ZonedDateTime date);

	}
}
