// Generated by RSD - Do not modify
package at.mspe.server.service.model;

import java.time.ZonedDateTime;
import java.util.Optional;

import at.mspe.server.service.model.mixins.SportEventBaseMixin;

public interface SportEvent {
	public interface Builder {}

	public interface Data extends _Base.BaseData, SportEvent, SportEventBaseMixin {
		public String key();

		public long version();

		public int participantCount();

		@Override
		public String name();

		@Override
		public ZonedDateTime date();

		@Override
		public String registrationUrl();

		@Override
		public Status status();

	}

	public interface DataBuilder extends Builder, _Base.BaseDataBuilder<SportEvent.Data> {
		public DataBuilder key(String key);

		public DataBuilder version(long version);

		public DataBuilder participantCount(int participantCount);

		public DataBuilder name(String name);

		public DataBuilder date(ZonedDateTime date);

		public DataBuilder registrationUrl(String registrationUrl);

		public DataBuilder status(Status status);

	}

	public interface Patch extends _Base.BaseData, SportEvent {
		public String key();

		public long version();

		public Optional<String> name();

		public Optional<ZonedDateTime> date();

		public _Base.Nillable<String> registrationUrl();

		public Optional<Status> status();

	}

	public interface PatchBuilder extends Builder, _Base.BaseDataBuilder<SportEvent.Patch> {
		public PatchBuilder key(String key);

		public PatchBuilder version(long version);

		public PatchBuilder name(String name);

		public PatchBuilder date(ZonedDateTime date);

		public PatchBuilder registrationUrl(String registrationUrl);

		public PatchBuilder status(Status status);

	}
}
