// Generated by RSD - Do not modify
package at.mspe.server.service.model;

public interface UpdateResult {

	public interface Data extends _Base.BaseData, UpdateResult {
		public String key();

		public long version();

	}

	public interface DataBuilder extends _Base.BaseDataBuilder<UpdateResult.Data> {
		public DataBuilder key(String key);

		public DataBuilder version(long version);

	}
}
