// Generated by RSD - Do not modify
import { decodeResponse, encodeValue, encodingType, safeExecute, type ServiceProps } from './_fetch-type-utils.ts';
import { api } from '../index.ts';

export function createEventParticipantService(props: ServiceProps<api.service.ErrorType>): api.service.EventParticipantService {
	return {
		get: fnGet(props),
		list: fnList(props),
		create: fnCreate(props),
		update: fnUpdate(props),
		delete: fnDelete(props),
		downloadCsv: fnDownloadCsv(props),
		uploadCsv: fnUploadCsv(props),
		checkCsv: fnCheckCsv(props),
	};
}
function fnGet(props: ServiceProps<api.service.ErrorType>): api.service.EventParticipantService['get'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onError, onCatch, final } = lifecycleHandlers;
	return async (eventKey: string, key: string) => {
		try {
			const $init = (await preFetch?.('get')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Content-Type', 'application/json');
			$init.headers = $headers;

			const $path = `${baseUrl}/api/sportevent/${encodeURIComponent(eventKey)}/participants/${encodeURIComponent(key)}`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isRecord);
				const $result = api.model.ParticipantFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('get', $result));
			} else if ($response.status === 404) {
				const err = {
					_type: 'NotFound',
					message: await $response.text(),
				} as const;
				return safeExecute(api.result.ERR(err), () => onError?.('get', err));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('get', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('get');
		}
	};
}

function fnList(props: ServiceProps<api.service.ErrorType>): api.service.EventParticipantService['list'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (eventKey: string) => {
		try {
			const $init = (await preFetch?.('list')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Content-Type', 'application/json');
			$init.headers = $headers;

			const $path = `${baseUrl}/api/sportevent/${encodeURIComponent(eventKey)}/participants/`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if ($response.status === 200) {
				const $data = await decodeResponse($response, v => api.utils.isTypedArray(v, api.utils.isRecord));
				const $result = $data.map(api.model.ParticipantFromJSON);
				return safeExecute(api.result.OK($result), () => onSuccess?.('list', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('list', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('list');
		}
	};
}

function fnCreate(props: ServiceProps<api.service.ErrorType>): api.service.EventParticipantService['create'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onError, onCatch, final } = lifecycleHandlers;
	return async (eventKey: string, participant: api.model.ParticipantNew, autoAssignCohort?: boolean) => {
		try {
			const $init = (await preFetch?.('create')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Content-Type', 'application/json');
			if (autoAssignCohort !== undefined) {
				$headers.append('autoAssignCohort', String(autoAssignCohort));
			}
			$init.headers = $headers;

			const $path = `${baseUrl}/api/sportevent/${encodeURIComponent(eventKey)}/participants/`;
			const $body = encodeValue(encodingType(props), api.model.ParticipantNewToJSON(participant));
			const $response = await fetchAPI($path, { ...$init, method: 'POST', body: $body });
			if ($response.status === 201) {
				const $data = await decodeResponse($response, api.utils.isString);
				return safeExecute(api.result.OK($data), () => onSuccess?.('create', $data));
			} else if ($response.status === 422) {
				const err = {
					_type: 'InvalidData',
					message: await $response.text(),
				} as const;
				return safeExecute(api.result.ERR(err), () => onError?.('create', err));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('create', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('create');
		}
	};
}

function fnUpdate(props: ServiceProps<api.service.ErrorType>): api.service.EventParticipantService['update'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onError, onCatch, final } = lifecycleHandlers;
	return async (eventKey: string, key: string, participant: api.model.ParticipantPatch, autoAssignCohort?: boolean) => {
		try {
			const $init = (await preFetch?.('update')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Content-Type', 'application/json');
			if (autoAssignCohort !== undefined) {
				$headers.append('autoAssignCohort', String(autoAssignCohort));
			}
			$init.headers = $headers;

			const $path = `${baseUrl}/api/sportevent/${encodeURIComponent(eventKey)}/participants/${encodeURIComponent(key)}`;
			const $body = encodeValue(encodingType(props), api.model.ParticipantPatchToJSON(participant));
			const $response = await fetchAPI($path, { ...$init, method: 'PATCH', body: $body });
			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isRecord);
				const $result = api.model.UpdateResultFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('update', $result));
			} else if ($response.status === 404) {
				const err = {
					_type: 'NotFound',
					message: await $response.text(),
				} as const;
				return safeExecute(api.result.ERR(err), () => onError?.('update', err));
			} else if ($response.status === 422) {
				const err = {
					_type: 'InvalidData',
					message: await $response.text(),
				} as const;
				return safeExecute(api.result.ERR(err), () => onError?.('update', err));
			} else if ($response.status === 412) {
				const err = {
					_type: 'StaleData',
					message: await $response.text(),
				} as const;
				return safeExecute(api.result.ERR(err), () => onError?.('update', err));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('update', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('update');
		}
	};
}

function fnDelete(props: ServiceProps<api.service.ErrorType>): api.service.EventParticipantService['delete'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onError, onCatch, final } = lifecycleHandlers;
	return async (eventKey: string, key: string, version?: number) => {
		try {
			const $init = (await preFetch?.('delete')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Content-Type', 'application/json');
			if (version !== undefined) {
				$headers.append('version', String(version));
			}
			$init.headers = $headers;

			const $path = `${baseUrl}/api/sportevent/${encodeURIComponent(eventKey)}/participants/${encodeURIComponent(key)}`;
			const $response = await fetchAPI($path, { ...$init, method: 'DELETE' });

			if ($response.status === 200) {
				return safeExecute(api.result.OK(api.result.Void), () => onSuccess?.('delete', api.result.Void));
			} else if ($response.status === 404) {
				const err = {
					_type: 'NotFound',
					message: await $response.text(),
				} as const;
				return safeExecute(api.result.ERR(err), () => onError?.('delete', err));
			} else if ($response.status === 412) {
				const err = {
					_type: 'StaleData',
					message: await $response.text(),
				} as const;
				return safeExecute(api.result.ERR(err), () => onError?.('delete', err));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('delete', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('delete');
		}
	};
}

function fnDownloadCsv(props: ServiceProps<api.service.ErrorType>): api.service.EventParticipantService['downloadCsv'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onError, onCatch, final } = lifecycleHandlers;
	return async (eventKey: string) => {
		try {
			const $init = (await preFetch?.('downloadCsv')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Content-Type', 'application/json');
			$init.headers = $headers;

			const $path = `${baseUrl}/api/sportevent/${encodeURIComponent(eventKey)}/participants/export/csv`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if ($response.status === 200) {
				const $data = await $response.blob();
				let fileName = 'unknown';
				const dispoHeader = $response.headers.get('Content-Disposition');
				if (dispoHeader?.includes('filename=')) {
					const fileNameWithQuotes = dispoHeader.substring(dispoHeader.indexOf('filename=') + 'filename='.length);
					fileName = fileNameWithQuotes.substring(1, fileNameWithQuotes.length - 1);
				}
				const $result = new File([$data], fileName, { type: $data.type });
				return safeExecute(api.result.OK($result), () => onSuccess?.('downloadCsv', $result));
			} else if ($response.status === 404) {
				const err = {
					_type: 'NotFound',
					message: await $response.text(),
				} as const;
				return safeExecute(api.result.ERR(err), () => onError?.('downloadCsv', err));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('downloadCsv', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('downloadCsv');
		}
	};
}

function fnUploadCsv(props: ServiceProps<api.service.ErrorType>): api.service.EventParticipantService['uploadCsv'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onError, onCatch, final } = lifecycleHandlers;
	return async (eventKey: string, csv: File) => {
		try {
			const $init = (await preFetch?.('uploadCsv')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$init.headers = $headers;

			const $path = `${baseUrl}/api/sportevent/${encodeURIComponent(eventKey)}/participants/import/csv`;
			const $body = new FormData();
			$body.append('csv', csv);
			const $response = await fetchAPI($path, { ...$init, method: 'POST', body: $body });
			if ($response.status === 200) {
				return safeExecute(api.result.OK(api.result.Void), () => onSuccess?.('uploadCsv', api.result.Void));
			} else if ($response.status === 404) {
				const err = {
					_type: 'NotFound',
					message: await $response.text(),
				} as const;
				return safeExecute(api.result.ERR(err), () => onError?.('uploadCsv', err));
			} else if ($response.status === 422) {
				const err = {
					_type: 'InvalidData',
					message: await $response.text(),
				} as const;
				return safeExecute(api.result.ERR(err), () => onError?.('uploadCsv', err));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('uploadCsv', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('uploadCsv');
		}
	};
}

function fnCheckCsv(props: ServiceProps<api.service.ErrorType>): api.service.EventParticipantService['checkCsv'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onError, onCatch, final } = lifecycleHandlers;
	return async (eventKey: string, csv: File) => {
		try {
			const $init = (await preFetch?.('checkCsv')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$init.headers = $headers;

			const $path = `${baseUrl}/api/sportevent/${encodeURIComponent(eventKey)}/participants/check/csv`;
			const $body = new FormData();
			$body.append('csv', csv);
			const $response = await fetchAPI($path, { ...$init, method: 'POST', body: $body });
			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isRecord);
				const $result = api.model.CheckCsvResultFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('checkCsv', $result));
			} else if ($response.status === 404) {
				const err = {
					_type: 'NotFound',
					message: await $response.text(),
				} as const;
				return safeExecute(api.result.ERR(err), () => onError?.('checkCsv', err));
			} else if ($response.status === 422) {
				const err = {
					_type: 'InvalidData',
					message: await $response.text(),
				} as const;
				return safeExecute(api.result.ERR(err), () => onError?.('checkCsv', err));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('checkCsv', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('checkCsv');
		}
	};
}

