// Generated by RSD - Do not modify
import { type Gender, isGender } from './Gender.ts';
import { checkProp, createIsStringTypeGuard, isNumber, isRecord, isString, propValue } from '../_type-utils.ts';

export type BirthyearCohortNew = {
	'@type': 'birthyear';
	readonly name: string;
	readonly gender: Gender;
	readonly min: number;
	readonly max: number;
};

export function isBirthyearCohortNew(value: unknown): value is BirthyearCohortNew {
	return (
		isRecord(value) &&
		checkProp(value, '@type', createIsStringTypeGuard('birthyear')) &&
		checkProp(value, 'name', isString) &&
		checkProp(value, 'gender', isGender) &&
		checkProp(value, 'min', isNumber) &&
		checkProp(value, 'max', isNumber)
	);
}

export function BirthyearCohortNewFromJSON($value: Record<string, unknown>): BirthyearCohortNew {
	const name = propValue('name', $value, isString);
	const gender = propValue('gender', $value, isGender);
	const min = propValue('min', $value, isNumber);
	const max = propValue('max', $value, isNumber);
	return {
		'@type': 'birthyear',
		name,
		gender,
		min,
		max,
	};
}

export function BirthyearCohortNewToJSON($value: BirthyearCohortNew): Record<string, unknown> {
	const name = $value.name;
	const gender = $value.gender;
	const min = $value.min;
	const max = $value.max;

	return {
		'@type': 'birthyear',
		name,
		gender,
		min,
		max,
	};
}
