// Generated by RSD - Do not modify
import { checkProp, isRecord, isString, propValue } from '../_type-utils.ts';

export type CheckCsvResultParticipant = {
	readonly key: string;
	readonly firstname: string;
	readonly lastname: string;
};

export function isCheckCsvResultParticipant(value: unknown): value is CheckCsvResultParticipant {
	return isRecord(value) &&
		checkProp(value, 'key', isString) &&
		checkProp(value, 'firstname', isString) &&
		checkProp(value, 'lastname', isString);
}

export function CheckCsvResultParticipantFromJSON($value: Record<string, unknown>): CheckCsvResultParticipant {
	const key = propValue('key', $value, isString);
	const firstname = propValue('firstname', $value, isString);
	const lastname = propValue('lastname', $value, isString);
	return {
		key,
		firstname,
		lastname,
	};
}

export function CheckCsvResultParticipantToJSON($value: CheckCsvResultParticipant): Record<string, unknown> {
	const key = $value.key;
	const firstname = $value.firstname;
	const lastname = $value.lastname;

	return {
		key,
		firstname,
		lastname,
	};
}

