// Generated by RSD - Do not modify
import { type CheckCsvResultParticipant, CheckCsvResultParticipantFromJSON, CheckCsvResultParticipantToJSON, isCheckCsvResultParticipant } from './CheckCsvResultParticipant.ts';
import { checkProp, createTypedArrayGuard, isRecord, propMappedListValue } from '../_type-utils.ts';

export type CheckCsvResult = {
	readonly unkownParticipants: CheckCsvResultParticipant[];
	readonly noTimeParticipants: CheckCsvResultParticipant[];
};

export function isCheckCsvResult(value: unknown): value is CheckCsvResult {
	return isRecord(value) &&
		checkProp(value, 'unkownParticipants', createTypedArrayGuard(isCheckCsvResultParticipant)) &&
		checkProp(value, 'noTimeParticipants', createTypedArrayGuard(isCheckCsvResultParticipant));
}

export function CheckCsvResultFromJSON($value: Record<string, unknown>): CheckCsvResult {
	const unkownParticipants = propMappedListValue('unkownParticipants', $value, isRecord, CheckCsvResultParticipantFromJSON);
	const noTimeParticipants = propMappedListValue('noTimeParticipants', $value, isRecord, CheckCsvResultParticipantFromJSON);
	return {
		unkownParticipants,
		noTimeParticipants,
	};
}

export function CheckCsvResultToJSON($value: CheckCsvResult): Record<string, unknown> {
	const unkownParticipants = $value.unkownParticipants.map(CheckCsvResultParticipantToJSON);
	const noTimeParticipants = $value.noTimeParticipants.map(CheckCsvResultParticipantToJSON);

	return {
		unkownParticipants,
		noTimeParticipants,
	};
}

