// Generated by RSD - Do not modify
import { checkProp, createIsStringTypeGuard, isRecord, isString, propValue } from '../_type-utils.ts';

export type GenericCohortNew = {
	'@type': 'generic';
	readonly name: string;
};

export function isGenericCohortNew(value: unknown): value is GenericCohortNew {
	return isRecord(value) &&
		checkProp(value, '@type', createIsStringTypeGuard('generic')) &&
		checkProp(value, 'name', isString);
}

export function GenericCohortNewFromJSON($value: Record<string, unknown>): GenericCohortNew {
	const name = propValue('name', $value, isString);
	return {
		'@type': 'generic',
		name,
	};
}

export function GenericCohortNewToJSON($value: GenericCohortNew): Record<string, unknown> {
	const name = $value.name;

	return {
		'@type': 'generic',
		name,
	};
}

