// Generated by RSD - Do not modify
import { checkProp, isRecord, isString, propValue } from '../_type-utils.ts';

export type ParticipantNew = {
	readonly firstname: string;
	readonly lastname: string;
	readonly team: string;
	readonly birthday: string;
};

export function isParticipantNew(value: unknown): value is ParticipantNew {
	return isRecord(value) &&
		checkProp(value, 'firstname', isString) &&
		checkProp(value, 'lastname', isString) &&
		checkProp(value, 'team', isString) &&
		checkProp(value, 'birthday', isString);
}

export function ParticipantNewFromJSON($value: Record<string, unknown>): ParticipantNew {
	const firstname = propValue('firstname', $value, isString);
	const lastname = propValue('lastname', $value, isString);
	const team = propValue('team', $value, isString);
	const birthday = propValue('birthday', $value, isString);
	return {
		firstname,
		lastname,
		team,
		birthday,
	};
}

export function ParticipantNewToJSON($value: ParticipantNew): Record<string, unknown> {
	const firstname = $value.firstname;
	const lastname = $value.lastname;
	const team = $value.team;
	const birthday = $value.birthday;

	return {
		firstname,
		lastname,
		team,
		birthday,
	};
}

