// Generated by RSD - Do not modify
import { isStatus, type Status } from './Status.ts';
import { checkOptProp, checkProp, isNull, isNumber, isRecord, isString, propValue } from '../_type-utils.ts';

export type SportEvent = {
	readonly key: string;
	readonly version: number;
	readonly participantCount: number;
	readonly name: string;
	readonly date: string;
	readonly registrationUrl?: string;
	readonly status: Status;
};

export function isSportEvent(value: unknown): value is SportEvent {
	return isRecord(value) &&
		checkProp(value, 'key', isString) &&
		checkProp(value, 'version', isNumber) &&
		checkProp(value, 'participantCount', isNumber) &&
		checkProp(value, 'name', isString) &&
		checkProp(value, 'date', isString) &&
		checkOptProp(value, 'registrationUrl', isString) &&
		checkProp(value, 'status', isStatus);
}

export function SportEventFromJSON($value: Record<string, unknown>): SportEvent {
	const key = propValue('key', $value, isString);
	const version = propValue('version', $value, isNumber);
	const participantCount = propValue('participantCount', $value, isNumber);
	const name = propValue('name', $value, isString);
	const date = propValue('date', $value, isString);
	const registrationUrl = propValue('registrationUrl', $value, isString, 'optional');
	const status = propValue('status', $value, isStatus);
	return {
		key,
		version,
		participantCount,
		name,
		date,
		registrationUrl,
		status,
	};
}

export function SportEventToJSON($value: SportEvent): Record<string, unknown> {
	const key = $value.key;
	const version = $value.version;
	const participantCount = $value.participantCount;
	const name = $value.name;
	const date = $value.date;
	const registrationUrl = $value.registrationUrl;
	const status = $value.status;

	return {
		key,
		version,
		participantCount,
		name,
		date,
		registrationUrl,
		status,
	};
}

export type SportEventPatch = {
	readonly key: string;
	readonly version: number;
	readonly name?: string;
	readonly date?: string;
	readonly registrationUrl?: string | null;
	readonly status?: Status;
};

export function isSportEventPatch(value: unknown): value is SportEventPatch {
	return isRecord(value) &&
		checkProp(value, 'key', isString) &&
		checkProp(value, 'version', isNumber) &&
		checkOptProp(value, 'name', isString) &&
		checkOptProp(value, 'date', isString) &&
		(checkOptProp(value, 'registrationUrl', isNull) || checkOptProp(value, 'registrationUrl', isString)) &&
		checkOptProp(value, 'status', isStatus);
}

export function SportEventPatchFromJSON($value: Record<string, unknown>): SportEventPatch {
	const key = propValue('key', $value, isString);
	const version = propValue('version', $value, isNumber);
	const name = propValue('name', $value, isString, 'optional');
	const date = propValue('date', $value, isString, 'optional');
	const registrationUrl = propValue('registrationUrl', $value, isString, 'optional_null');
	const status = propValue('status', $value, isStatus, 'optional');
	return {
		key,
		version,
		name,
		date,
		registrationUrl,
		status,
	};
}

export function SportEventPatchToJSON($value: SportEventPatch): Record<string, unknown> {
	const key = $value.key;
	const version = $value.version;
	const name = $value.name;
	const date = $value.date;
	const registrationUrl = $value.registrationUrl;
	const status = $value.status;

	return {
		key,
		version,
		name,
		date,
		registrationUrl,
		status,
	};
}

