// Generated by RSD - Do not modify
import { checkProp, isRecord, isString, propValue } from '../_type-utils.ts';

export type SportEventNew = {
	readonly name: string;
	readonly date: string;
};

export function isSportEventNew(value: unknown): value is SportEventNew {
	return isRecord(value) &&
		checkProp(value, 'name', isString) &&
		checkProp(value, 'date', isString);
}

export function SportEventNewFromJSON($value: Record<string, unknown>): SportEventNew {
	const name = propValue('name', $value, isString);
	const date = propValue('date', $value, isString);
	return {
		name,
		date,
	};
}

export function SportEventNewToJSON($value: SportEventNew): Record<string, unknown> {
	const name = $value.name;
	const date = $value.date;

	return {
		name,
		date,
	};
}

