// Generated by RSD - Do not modify
export type Status = 'PLANNING' | 'REGISTRATION' | 'ACTIVE' | 'FINISHED';

export function isStatus(value: unknown) {
	return value === 'PLANNING' || value === 'REGISTRATION' || value === 'ACTIVE' || value === 'FINISHED';
}
