// Generated by RSD - Do not modify
import { checkProp, isNumber, isRecord, isString, propValue } from '../_type-utils.ts';

export type UpdateResult = {
	readonly key: string;
	readonly version: number;
};

export function isUpdateResult(value: unknown): value is UpdateResult {
	return isRecord(value) &&
		checkProp(value, 'key', isString) &&
		checkProp(value, 'version', isNumber);
}

export function UpdateResultFromJSON($value: Record<string, unknown>): UpdateResult {
	const key = propValue('key', $value, isString);
	const version = propValue('version', $value, isNumber);
	return {
		key,
		version,
	};
}

export function UpdateResultToJSON($value: UpdateResult): Record<string, unknown> {
	const key = $value.key;
	const version = $value.version;

	return {
		key,
		version,
	};
}

