// Generated by RSD - Do not modify
package at.mspe.server.service;

import java.nio.file.Path;

import at.mspe.server.service.model._Base;
import at.mspe.server.service.model.RSDBlob;
import at.mspe.server.service.model.RSDFile;

public interface BuilderFactory {
	public <T extends _Base.BaseDataBuilder<?>> T builder(Class<T> type);

	public RSDBlob createBlob(Path file, String mimeType);

	public RSDFile createFile(Path file, String mimeType, String filename);
}
