// Generated by RSD - Do not modify
package at.mspe.server.service;

import at.mspe.server.service.model._Base;

public interface BuilderFactory {
	public <T extends _Base.BaseDataBuilder<?>> T builder(Class<T> type);
}
