// Generated by RSD - Do not modify
package at.mspe.server.service;

import java.util.List;

import at.mspe.server.service.model.Cohort;
import at.mspe.server.service.model.CohortNew;

public interface EventCohortService {
	public Cohort.Data get(BuilderFactory _factory, String eventKey);

	public List<Cohort.Data> list(BuilderFactory _factory, String eventKey);

	public String create(BuilderFactory _factory, String eventKey, CohortNew.Data cohort);

	public void update(BuilderFactory _factory, String eventKey, String key, Cohort.Patch cohort);

	public void delete(BuilderFactory _factory, String eventKey, String key);

}
