// Generated by RSD - Do not modify
package at.mspe.server.service;

import java.util.List;

import at.mspe.server.service.model.Participant;
import at.mspe.server.service.model.ParticipantNew;

public interface EventParticipantService {
	public Participant.Data get(BuilderFactory _factory, String eventKey);

	public List<Participant.Data> list(BuilderFactory _factory, String eventKey);

	public String create(BuilderFactory _factory, String eventKey, ParticipantNew.Data participant);

	public void update(BuilderFactory _factory, String eventKey, String key, Participant.Patch participant);

	public void delete(BuilderFactory _factory, String eventKey, String key);

}
