// Generated by RSD - Do not modify
package at.mspe.server.service;

import java.util.List;
import java.util.Optional;
import java.util.OptionalLong;

import at.mspe.server.service.model.CheckCsvResult;
import at.mspe.server.service.model.Participant;
import at.mspe.server.service.model.ParticipantNew;
import at.mspe.server.service.model.RSDFile;
import at.mspe.server.service.model.UpdateResult;

public interface EventParticipantService {
	public Participant.Data get(BuilderFactory _factory, String eventKey, String key)
			throws NotFoundException;

	public List<Participant.Data> list(BuilderFactory _factory, String eventKey)
			throws NotFoundException;

	public String create(BuilderFactory _factory, String eventKey, ParticipantNew.Data participant, Optional<Boolean> autoAssignCohort)
			throws NotFoundException,
			InvalidDataException;

	public UpdateResult.Data update(BuilderFactory _factory, String eventKey, String key, Participant.Patch participant, Optional<Boolean> autoAssignCohort)
			throws NotFoundException,
			InvalidDataException,
			StaleDataException;

	public void delete(BuilderFactory _factory, String eventKey, String key, OptionalLong version)
			throws NotFoundException,
			StaleDataException;

	public RSDFile downloadCsv(BuilderFactory _factory, String eventKey)
			throws NotFoundException;

	public void uploadCsv(BuilderFactory _factory, String eventKey, RSDFile csv)
			throws NotFoundException,
			InvalidDataException;

	public CheckCsvResult.Data checkCsv(BuilderFactory _factory, String eventKey, RSDFile csv)
			throws NotFoundException,
			InvalidDataException;

}
