// Generated by RSD - Do not modify
package at.mspe.server.service;

import java.util.List;

import at.mspe.server.service.model.Participant;
import at.mspe.server.service.model.ParticipantNew;
import at.mspe.server.service.model.UpdateResult;

public interface EventParticipantService {
	public Participant.Data get(BuilderFactory _factory, String eventKey, String key)
			throws NotFoundException;

	public List<Participant.Data> list(BuilderFactory _factory, String eventKey)
			throws NotFoundException;

	public String create(BuilderFactory _factory, String eventKey, ParticipantNew.Data participant)
			throws NotFoundException,
			InvalidDataException;

	public UpdateResult.Data update(BuilderFactory _factory, String eventKey, String key, Participant.Patch participant)
			throws NotFoundException,
			InvalidDataException,
			StaleDataException;

	public void delete(BuilderFactory _factory, String eventKey, String key, Long version)
			throws NotFoundException,
			StaleDataException;

}
