// Generated by RSD - Do not modify
package at.mspe.server.service;

public class InvalidDataException extends RSDException {
	public InvalidDataException(String message) {
		super(Type.InvalidData, message);
	}
}
