// Generated by RSD - Do not modify
package at.mspe.server.service;

public class NotFoundException extends RSDException {
	public NotFoundException(String message) {
		super(Type.NotFound, message);
	}
}
