// Generated by RSD - Do not modify
package at.mspe.server.service;

import at.mspe.server.service.model._Base;

public class RSDException extends RuntimeException {
	public enum Type {
		NotFound,
		InvalidData,
		StaleData;
	}

	public final Type type;

	RSDException(Type type, String message) {
		super(message);
		this.type = type;
	}

	public static class RSDStructuredDataException extends RSDException {
		public final _Base.BaseData data;

		public RSDStructuredDataException(Type type, String message, _Base.BaseData data) {
			super(type, message);
			this.data = data;
		}
	}
}
