// Generated by RSD - Do not modify
package at.mspe.server.service;

import java.util.List;

import at.mspe.server.service.model.Participant;
import at.mspe.server.service.model.SportEvent;
import at.mspe.server.service.model.SportEventNew;

public interface SportEventService {
	public SportEvent.Data get(BuilderFactory _factory, String key);

	public List<SportEvent.Data> list(BuilderFactory _factory);

	public String create(BuilderFactory _factory, SportEventNew.Data participant);

	public void update(BuilderFactory _factory, String key, Participant.Patch participant);

	public void delete(BuilderFactory _factory, String key);

}
