// Generated by RSD - Do not modify
package at.mspe.server.service;

import java.util.List;
import java.util.OptionalLong;

import at.mspe.server.service.model.SportEvent;
import at.mspe.server.service.model.SportEventNew;
import at.mspe.server.service.model.UpdateResult;

public interface SportEventService {
	public SportEvent.Data get(BuilderFactory _factory, String key)
			throws NotFoundException;

	public List<SportEvent.Data> list(BuilderFactory _factory);

	public String create(BuilderFactory _factory, SportEventNew.Data event)
			throws InvalidDataException;

	public UpdateResult.Data update(BuilderFactory _factory, String key, SportEvent.Patch event)
			throws NotFoundException,
			InvalidDataException,
			StaleDataException;

	public void delete(BuilderFactory _factory, String key, OptionalLong version)
			throws NotFoundException,
			StaleDataException;

}
