// Generated by RSD - Do not modify
package at.mspe.server.service;

public class StaleDataException extends RSDException {
	public StaleDataException(String message) {
		super(Type.StaleData, message);
	}
}
