// Generated by RSD - Do not modify
package at.mspe.server.service.impl;

import java.util.List;

import jakarta.enterprise.context.ApplicationScoped;

import at.mspe.server.service.BuilderFactory;
import at.mspe.server.service.EventCohortService;
import at.mspe.server.service.model.Cohort;
import at.mspe.server.service.model.CohortNew;

@ApplicationScoped
public class EventCohortServiceImpl implements EventCohortService {
	private final GetHandler getHandler;
	private final ListHandler listHandler;
	private final CreateHandler createHandler;
	private final UpdateHandler updateHandler;
	private final DeleteHandler deleteHandler;

	public EventCohortServiceImpl(GetHandler getHandler, ListHandler listHandler, CreateHandler createHandler,
			UpdateHandler updateHandler, DeleteHandler deleteHandler) {
		this.getHandler = getHandler;
		this.listHandler = listHandler;
		this.createHandler = createHandler;
		this.updateHandler = updateHandler;
		this.deleteHandler = deleteHandler;
	}

	@Override
	public Cohort.Data get(BuilderFactory _factory, String eventKey) {
		return getHandler.get(_factory, eventKey);
	}

	@Override
	public List<Cohort.Data> list(BuilderFactory _factory, String eventKey) {
		return listHandler.list(_factory, eventKey);
	}

	@Override
	public String create(BuilderFactory _factory, String eventKey, CohortNew.Data cohort) {
		return createHandler.create(_factory, eventKey, cohort);
	}

	@Override
	public void update(BuilderFactory _factory, String eventKey, String key, Cohort.Patch cohort) {
		updateHandler.update(_factory, eventKey, key, cohort);
	}

	@Override
	public void delete(BuilderFactory _factory, String eventKey, String key) {
		deleteHandler.delete(_factory, eventKey, key);
	}

	public interface GetHandler {
		public Cohort.Data get(BuilderFactory _factory, String eventKey);
	}

	public interface ListHandler {
		public List<Cohort.Data> list(BuilderFactory _factory, String eventKey);
	}

	public interface CreateHandler {
		public String create(BuilderFactory _factory, String eventKey, CohortNew.Data cohort);
	}

	public interface UpdateHandler {
		public void update(BuilderFactory _factory, String eventKey, String key, Cohort.Patch cohort);
	}

	public interface DeleteHandler {
		public void delete(BuilderFactory _factory, String eventKey, String key);
	}

}
