// Generated by RSD - Do not modify
package at.mspe.server.service.impl;

import java.util.List;

import jakarta.inject.Singleton;

import at.mspe.server.service.BuilderFactory;
import at.mspe.server.service.EventParticipantService;
import at.mspe.server.service.model.Participant;
import at.mspe.server.service.model.ParticipantNew;

@Singleton
public class EventParticipantServiceImpl implements EventParticipantService {
	private final GetHandler getHandler;
	private final ListHandler listHandler;
	private final CreateHandler createHandler;
	private final UpdateHandler updateHandler;
	private final DeleteHandler deleteHandler;

	public EventParticipantServiceImpl(GetHandler getHandler, ListHandler listHandler, CreateHandler createHandler, UpdateHandler updateHandler, DeleteHandler deleteHandler) {
		this.getHandler = getHandler;
		this.listHandler = listHandler;
		this.createHandler = createHandler;
		this.updateHandler = updateHandler;
		this.deleteHandler = deleteHandler;
	}

	@Override
	public Participant.Data get(BuilderFactory _factory, String eventKey) {
		return getHandler.get(_factory, eventKey);
	}

	@Override
	public List<Participant.Data> list(BuilderFactory _factory, String eventKey) {
		return listHandler.list(_factory, eventKey);
	}

	@Override
	public String create(BuilderFactory _factory, String eventKey, ParticipantNew.Data participant) {
		return createHandler.create(_factory, eventKey, participant);
	}

	@Override
	public void update(BuilderFactory _factory, String eventKey, String key, Participant.Patch participant) {
		updateHandler.update(_factory, eventKey, key, participant);
	}

	@Override
	public void delete(BuilderFactory _factory, String eventKey, String key) {
		deleteHandler.delete(_factory, eventKey, key);
	}

	public interface GetHandler {
		public Participant.Data get(BuilderFactory _factory, String eventKey);
	}

	public interface ListHandler {
		public List<Participant.Data> list(BuilderFactory _factory, String eventKey);
	}

	public interface CreateHandler {
		public String create(BuilderFactory _factory, String eventKey, ParticipantNew.Data participant);
	}

	public interface UpdateHandler {
		public void update(BuilderFactory _factory, String eventKey, String key, Participant.Patch participant);
	}

	public interface DeleteHandler {
		public void delete(BuilderFactory _factory, String eventKey, String key);
	}

}
