// Generated by RSD - Do not modify
package at.mspe.server.service.impl;

import java.util.List;
import java.util.Optional;
import java.util.OptionalLong;

import jakarta.enterprise.context.ApplicationScoped;

import at.mspe.server.service.BuilderFactory;
import at.mspe.server.service.EventParticipantService;
import at.mspe.server.service.InvalidDataException;
import at.mspe.server.service.model.CheckCsvResult;
import at.mspe.server.service.model.Participant;
import at.mspe.server.service.model.ParticipantNew;
import at.mspe.server.service.model.RSDFile;
import at.mspe.server.service.model.UpdateResult;
import at.mspe.server.service.NotFoundException;
import at.mspe.server.service.StaleDataException;

@ApplicationScoped
public class EventParticipantServiceImpl implements EventParticipantService {
	private final GetHandler getHandler;
	private final ListHandler listHandler;
	private final CreateHandler createHandler;
	private final UpdateHandler updateHandler;
	private final DeleteHandler deleteHandler;
	private final DownloadCsvHandler downloadCsvHandler;
	private final UploadCsvHandler uploadCsvHandler;
	private final CheckCsvHandler checkCsvHandler;

	public EventParticipantServiceImpl(GetHandler getHandler, ListHandler listHandler, CreateHandler createHandler, UpdateHandler updateHandler, DeleteHandler deleteHandler, DownloadCsvHandler downloadCsvHandler, UploadCsvHandler uploadCsvHandler, CheckCsvHandler checkCsvHandler) {
		this.getHandler = getHandler;
		this.listHandler = listHandler;
		this.createHandler = createHandler;
		this.updateHandler = updateHandler;
		this.deleteHandler = deleteHandler;
		this.downloadCsvHandler = downloadCsvHandler;
		this.uploadCsvHandler = uploadCsvHandler;
		this.checkCsvHandler = checkCsvHandler;
	}

	@Override
	public Participant.Data get(BuilderFactory _factory, String eventKey, String key)
			throws NotFoundException {
		return getHandler.get(_factory, eventKey, key);
	}

	@Override
	public List<Participant.Data> list(BuilderFactory _factory, String eventKey)
			throws NotFoundException {
		return listHandler.list(_factory, eventKey);
	}

	@Override
	public String create(BuilderFactory _factory, String eventKey, ParticipantNew.Data participant, Optional<Boolean> autoAssignCohort)
			throws NotFoundException,
			InvalidDataException {
		return createHandler.create(_factory, eventKey, participant, autoAssignCohort);
	}

	@Override
	public UpdateResult.Data update(BuilderFactory _factory, String eventKey, String key, Participant.Patch participant, Optional<Boolean> autoAssignCohort)
			throws NotFoundException,
			InvalidDataException,
			StaleDataException {
		return updateHandler.update(_factory, eventKey, key, participant, autoAssignCohort);
	}

	@Override
	public void delete(BuilderFactory _factory, String eventKey, String key, OptionalLong version)
			throws NotFoundException,
			StaleDataException {
		deleteHandler.delete(_factory, eventKey, key, version);
	}

	@Override
	public RSDFile downloadCsv(BuilderFactory _factory, String eventKey)
			throws NotFoundException {
		return downloadCsvHandler.downloadCsv(_factory, eventKey);
	}

	@Override
	public void uploadCsv(BuilderFactory _factory, String eventKey, RSDFile csv)
			throws NotFoundException,
			InvalidDataException {
		uploadCsvHandler.uploadCsv(_factory, eventKey, csv);
	}

	@Override
	public CheckCsvResult.Data checkCsv(BuilderFactory _factory, String eventKey, RSDFile csv)
			throws NotFoundException,
			InvalidDataException {
		return checkCsvHandler.checkCsv(_factory, eventKey, csv);
	}

	public interface GetHandler {
		public Participant.Data get(BuilderFactory _factory, String eventKey, String key)
				throws NotFoundException;
	}

	public interface ListHandler {
		public List<Participant.Data> list(BuilderFactory _factory, String eventKey)
				throws NotFoundException;
	}

	public interface CreateHandler {
		public String create(BuilderFactory _factory, String eventKey, ParticipantNew.Data participant, Optional<Boolean> autoAssignCohort)
				throws NotFoundException,
				InvalidDataException;
	}

	public interface UpdateHandler {
		public UpdateResult.Data update(BuilderFactory _factory, String eventKey, String key, Participant.Patch participant, Optional<Boolean> autoAssignCohort)
				throws NotFoundException,
				InvalidDataException,
				StaleDataException;
	}

	public interface DeleteHandler {
		public void delete(BuilderFactory _factory, String eventKey, String key, OptionalLong version)
				throws NotFoundException,
				StaleDataException;
	}

	public interface DownloadCsvHandler {
		public RSDFile downloadCsv(BuilderFactory _factory, String eventKey)
				throws NotFoundException;
	}

	public interface UploadCsvHandler {
		public void uploadCsv(BuilderFactory _factory, String eventKey, RSDFile csv)
				throws NotFoundException,
				InvalidDataException;
	}

	public interface CheckCsvHandler {
		public CheckCsvResult.Data checkCsv(BuilderFactory _factory, String eventKey, RSDFile csv)
				throws NotFoundException,
				InvalidDataException;
	}

}
