// Generated by RSD - Do not modify
package at.mspe.server.service.impl;

import java.util.List;

import jakarta.inject.Singleton;

import at.mspe.server.service.BuilderFactory;
import at.mspe.server.service.model.Participant;
import at.mspe.server.service.model.SportEvent;
import at.mspe.server.service.model.SportEventNew;
import at.mspe.server.service.SportEventService;

@Singleton
public class SportEventServiceImpl implements SportEventService {
	private final GetHandler getHandler;
	private final ListHandler listHandler;
	private final CreateHandler createHandler;
	private final UpdateHandler updateHandler;
	private final DeleteHandler deleteHandler;

	public SportEventServiceImpl(GetHandler getHandler, ListHandler listHandler, CreateHandler createHandler, UpdateHandler updateHandler, DeleteHandler deleteHandler) {
		this.getHandler = getHandler;
		this.listHandler = listHandler;
		this.createHandler = createHandler;
		this.updateHandler = updateHandler;
		this.deleteHandler = deleteHandler;
	}

	@Override
	public SportEvent.Data get(BuilderFactory _factory, String key) {
		return getHandler.get(_factory, key);
	}

	@Override
	public List<SportEvent.Data> list(BuilderFactory _factory) {
		return listHandler.list(_factory);
	}

	@Override
	public String create(BuilderFactory _factory, SportEventNew.Data participant) {
		return createHandler.create(_factory, participant);
	}

	@Override
	public void update(BuilderFactory _factory, String key, Participant.Patch participant) {
		updateHandler.update(_factory, key, participant);
	}

	@Override
	public void delete(BuilderFactory _factory, String key) {
		deleteHandler.delete(_factory, key);
	}

	public interface GetHandler {
		public SportEvent.Data get(BuilderFactory _factory, String key);
	}

	public interface ListHandler {
		public List<SportEvent.Data> list(BuilderFactory _factory);
	}

	public interface CreateHandler {
		public String create(BuilderFactory _factory, SportEventNew.Data participant);
	}

	public interface UpdateHandler {
		public void update(BuilderFactory _factory, String key, Participant.Patch participant);
	}

	public interface DeleteHandler {
		public void delete(BuilderFactory _factory, String key);
	}

}
