// Generated by RSD - Do not modify
package at.mspe.server.service.impl;

import java.util.List;

import jakarta.enterprise.context.ApplicationScoped;

import at.mspe.server.service.BuilderFactory;
import at.mspe.server.service.InvalidDataException;
import at.mspe.server.service.model.SportEvent;
import at.mspe.server.service.model.SportEventNew;
import at.mspe.server.service.model.UpdateResult;
import at.mspe.server.service.NotFoundException;
import at.mspe.server.service.SportEventService;
import at.mspe.server.service.StaleDataException;

@ApplicationScoped
public class SportEventServiceImpl implements SportEventService {
	private final GetHandler getHandler;
	private final ListHandler listHandler;
	private final CreateHandler createHandler;
	private final UpdateHandler updateHandler;
	private final DeleteHandler deleteHandler;

	public SportEventServiceImpl(GetHandler getHandler, ListHandler listHandler, CreateHandler createHandler, UpdateHandler updateHandler, DeleteHandler deleteHandler) {
		this.getHandler = getHandler;
		this.listHandler = listHandler;
		this.createHandler = createHandler;
		this.updateHandler = updateHandler;
		this.deleteHandler = deleteHandler;
	}

	@Override
	public SportEvent.Data get(BuilderFactory _factory, String key)
			throws NotFoundException {
		return getHandler.get(_factory, key);
	}

	@Override
	public List<SportEvent.Data> list(BuilderFactory _factory) {
		return listHandler.list(_factory);
	}

	@Override
	public String create(BuilderFactory _factory, SportEventNew.Data event)
			throws InvalidDataException {
		return createHandler.create(_factory, event);
	}

	@Override
	public UpdateResult.Data update(BuilderFactory _factory, String key, SportEvent.Patch event)
			throws NotFoundException,
			InvalidDataException,
			StaleDataException {
		return updateHandler.update(_factory, key, event);
	}

	@Override
	public void delete(BuilderFactory _factory, String key, Long version)
			throws NotFoundException,
			StaleDataException {
		deleteHandler.delete(_factory, key, version);
	}

	public interface GetHandler {
		public SportEvent.Data get(BuilderFactory _factory, String key)
				throws NotFoundException;
	}

	public interface ListHandler {
		public List<SportEvent.Data> list(BuilderFactory _factory);
	}

	public interface CreateHandler {
		public String create(BuilderFactory _factory, SportEventNew.Data event)
				throws InvalidDataException;
	}

	public interface UpdateHandler {
		public UpdateResult.Data update(BuilderFactory _factory, String key, SportEvent.Patch event)
				throws NotFoundException,
				InvalidDataException,
				StaleDataException;
	}

	public interface DeleteHandler {
		public void delete(BuilderFactory _factory, String key, Long version)
				throws NotFoundException,
				StaleDataException;
	}

}
