// Generated by RSD - Do not modify
package at.mspe.server.rest.model;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Optional;

import at.mspe.server.service.model.RSDBlob;

public class _BlobImpl implements RSDBlob {
	private final Path file;
	private final String mimeType;

	_BlobImpl(Path file, String mimeType) {
		this.file = file;
		this.mimeType = mimeType;
	}

	@Override
	public InputStream stream() {
		try {
			return Files.newInputStream(file);
		} catch(IOException e) {
			throw new IllegalStateException(e);
		}
	}

	@Override
	public Optional<String> mimeType() {
		return Optional.ofNullable(mimeType);
	}

	public static RSDBlob of(Path file, String mimeType) {
		return new _BlobImpl(file, mimeType);
	}
}
