// Generated by RSD - Do not modify
package at.mspe.server.rest.model;

import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;

import at.mspe.server.service.model.BirthyearCohortNew;

public class BirthyearCohortNewDataImpl extends _BaseDataImpl implements BirthyearCohortNew.Data {
	BirthyearCohortNewDataImpl(JsonObject data) {
		super(data);
	}

	public String name() {
		return _JsonUtils.mapString(data, "name");
	}

	public int min() {
		return _JsonUtils.mapInt(data, "min");
	}

	public int max() {
		return _JsonUtils.mapInt(data, "max", 0);
	}

	public static BirthyearCohortNew.Data of(JsonObject obj) {
		return new BirthyearCohortNewDataImpl(obj);
	}

	public String toString() {
		return getClass().getSimpleName();
	}

	public static class DataBuilderImpl implements BirthyearCohortNew.DataBuilder {
		private JsonObjectBuilder $builder = Json.createObjectBuilder();

		public DataBuilderImpl() {
			$builder.add("@type", "birthyear");
		}

		public BirthyearCohortNew.DataBuilder name(String name) {
			if (name == null) {
				return this;
			}
			$builder.add("name", name);
			return this;
		}

		public BirthyearCohortNew.DataBuilder min(int min) {
			$builder.add("min", min);
			return this;
		}

		public BirthyearCohortNew.DataBuilder max(int max) {
			$builder.add("max", max);
			return this;
		}

		public BirthyearCohortNew.Data build() {
			return new BirthyearCohortNewDataImpl($builder.build());
		}
	}

	public static BirthyearCohortNew.DataBuilder builder() {
		return new DataBuilderImpl();
	}
}
