// Generated by RSD - Do not modify
package at.mspe.server.rest.model;

import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;

import at.mspe.server.service.model.BirthyearCohort;
import at.mspe.server.service.model.Gender;

public class BirthyearCohortDataImpl extends _BaseDataImpl implements BirthyearCohort.Data {
	BirthyearCohortDataImpl(JsonObject data) {
		super(data);
	}

	@Override
	public String key() {
		return _JsonUtils.mapString(data, "key");
	}

	@Override
	public long version() {
		return _JsonUtils.mapLong(data, "version");
	}

	@Override
	public int participantCount() {
		return _JsonUtils.mapInt(data, "participantCount");
	}

	@Override
	public String name() {
		return _JsonUtils.mapString(data, "name");
	}

	@Override
	public Gender gender() {
		return _JsonUtils.mapLiteral(data, "gender", Gender::valueOf);
	}

	@Override
	public int min() {
		return _JsonUtils.mapInt(data, "min");
	}

	@Override
	public int max() {
		return _JsonUtils.mapInt(data, "max");
	}

	public static BirthyearCohort.Data of(JsonObject obj) {
		return new BirthyearCohortDataImpl(obj);
	}

	public String toString() {
		return "%s[%s=%s@%s=%s]".formatted(getClass().getSimpleName(), "key", key(), "version", version());
	}

	public static class DataBuilderImpl implements BirthyearCohort.DataBuilder {
		private JsonObjectBuilder $builder = Json.createObjectBuilder();

		public DataBuilderImpl() {
			$builder.add("@type", "birthyear");
		}

		@Override
		public BirthyearCohort.DataBuilder key(String key) {
			$builder.add("key", key);
			return this;
		}

		@Override
		public BirthyearCohort.DataBuilder version(long version) {
			$builder.add("version", version);
			return this;
		}

		@Override
		public BirthyearCohort.DataBuilder participantCount(int participantCount) {
			$builder.add("participantCount", participantCount);
			return this;
		}

		@Override
		public BirthyearCohort.DataBuilder name(String name) {
			if (name == null) {
				return this;
			}
			$builder.add("name", name);
			return this;
		}

		@Override
		public BirthyearCohort.DataBuilder gender(Gender gender) {
			if (gender == null) {
				return this;
			}
			$builder.add("gender", gender.toString());
			return this;
		}

		@Override
		public BirthyearCohort.DataBuilder min(int min) {
			$builder.add("min", min);
			return this;
		}

		@Override
		public BirthyearCohort.DataBuilder max(int max) {
			$builder.add("max", max);
			return this;
		}

		public BirthyearCohort.Data build() {
			return new BirthyearCohortDataImpl($builder.build());
		}
	}

	public static BirthyearCohort.DataBuilder builder() {
		return new DataBuilderImpl();
	}
}
