// Generated by RSD - Do not modify
package at.mspe.server.rest.model;

import java.util.Optional;
import java.util.OptionalInt;

import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;

import at.mspe.server.service.model.BirthyearCohort;

public class BirthyearCohortPatchImpl extends _BaseDataImpl implements BirthyearCohort.Patch {
	BirthyearCohortPatchImpl(JsonObject data) {
		super(data);
	}

	public String key() {
		return _JsonUtils.mapString(data, "key");
	}

	public long version() {
		return _JsonUtils.mapLong(data, "version");
	}

	public Optional<String> name() {
		return _JsonUtils.mapOptString(data, "name");
	}

	public OptionalInt min() {
		return _JsonUtils.mapOptInt(data, "min");
	}

	public OptionalInt max() {
		return _JsonUtils.mapOptInt(data, "max");
	}

	public static class PatchBuilderImpl implements BirthyearCohort.PatchBuilder {
		private JsonObjectBuilder $builder = Json.createObjectBuilder();

		public PatchBuilderImpl() {
			$builder.add("@type", "patch:birthyear");
		}

		public BirthyearCohort.PatchBuilder key(String key) {
			$builder.add("key", key);
			return this;
		}

		public BirthyearCohort.PatchBuilder version(long version) {
			$builder.add("version", version);
			return this;
		}

		@Override
		public BirthyearCohort.PatchBuilder name(String name) {
			$builder.add("name", name);
			return this;
		}

		@Override
		public BirthyearCohort.PatchBuilder min(int min) {
			$builder.add("min", min);
			return this;
		}

		@Override
		public BirthyearCohort.PatchBuilder max(int max) {
			$builder.add("max", max);
			return this;
		}

		@Override
		public BirthyearCohort.Patch build() {
			return new BirthyearCohortPatchImpl($builder.build());
		}
	}

	public static BirthyearCohort.Patch of(JsonObject obj) {
		return new BirthyearCohortPatchImpl(obj);
	}

	public static PatchBuilderImpl builder() {
		return new PatchBuilderImpl();
	}
}
