// Generated by RSD - Do not modify
package at.mspe.server.rest.model;

import java.util.List;

import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;

import at.mspe.server.service.model.CheckCsvResult;
import at.mspe.server.service.model.CheckCsvResultParticipant;

public class CheckCsvResultDataImpl extends _BaseDataImpl implements CheckCsvResult.Data {
	CheckCsvResultDataImpl(JsonObject data) {
		super(data);
	}

	@Override
	public List<CheckCsvResultParticipant.Data> unkownParticipants() {
		return _JsonUtils.mapObjects(data, "unkownParticipants", CheckCsvResultParticipantDataImpl::of);
	}

	@Override
	public List<CheckCsvResultParticipant.Data> noTimeParticipants() {
		return _JsonUtils.mapObjects(data, "noTimeParticipants", CheckCsvResultParticipantDataImpl::of);
	}

	public static CheckCsvResult.Data of(JsonObject obj) {
		return new CheckCsvResultDataImpl(obj);
	}

	public String toString() {
		return getClass().getSimpleName();
	}

	public static class DataBuilderImpl implements CheckCsvResult.DataBuilder {
		private JsonObjectBuilder $builder = Json.createObjectBuilder();

		@Override
		public CheckCsvResult.DataBuilder unkownParticipants(List<CheckCsvResultParticipant.Data> unkownParticipants) {
			if (unkownParticipants == null) {
				return this;
			}
			$builder.add("unkownParticipants", _JsonUtils.toJsonValueArray(unkownParticipants, $e -> ((_BaseDataImpl) $e).data));
			return this;
		}

		@Override
		public CheckCsvResult.DataBuilder noTimeParticipants(List<CheckCsvResultParticipant.Data> noTimeParticipants) {
			if (noTimeParticipants == null) {
				return this;
			}
			$builder.add("noTimeParticipants", _JsonUtils.toJsonValueArray(noTimeParticipants, $e -> ((_BaseDataImpl) $e).data));
			return this;
		}

		public CheckCsvResult.Data build() {
			return new CheckCsvResultDataImpl($builder.build());
		}
	}

	public static CheckCsvResult.DataBuilder builder() {
		return new DataBuilderImpl();
	}
}
