// Generated by RSD - Do not modify
package at.mspe.server.rest.model;

import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;

import at.mspe.server.service.model.CheckCsvResultParticipant;

public class CheckCsvResultParticipantDataImpl extends _BaseDataImpl implements CheckCsvResultParticipant.Data {
	CheckCsvResultParticipantDataImpl(JsonObject data) {
		super(data);
	}

	@Override
	public String key() {
		return _JsonUtils.mapString(data, "key");
	}

	@Override
	public String firstname() {
		return _JsonUtils.mapString(data, "firstname");
	}

	@Override
	public String lastname() {
		return _JsonUtils.mapString(data, "lastname");
	}

	public static CheckCsvResultParticipant.Data of(JsonObject obj) {
		return new CheckCsvResultParticipantDataImpl(obj);
	}

	public String toString() {
		return getClass().getSimpleName();
	}

	public static class DataBuilderImpl implements CheckCsvResultParticipant.DataBuilder {
		private JsonObjectBuilder $builder = Json.createObjectBuilder();

		@Override
		public CheckCsvResultParticipant.DataBuilder key(String key) {
			if (key == null) {
				return this;
			}
			$builder.add("key", key);
			return this;
		}

		@Override
		public CheckCsvResultParticipant.DataBuilder firstname(String firstname) {
			if (firstname == null) {
				return this;
			}
			$builder.add("firstname", firstname);
			return this;
		}

		@Override
		public CheckCsvResultParticipant.DataBuilder lastname(String lastname) {
			if (lastname == null) {
				return this;
			}
			$builder.add("lastname", lastname);
			return this;
		}

		public CheckCsvResultParticipant.Data build() {
			return new CheckCsvResultParticipantDataImpl($builder.build());
		}
	}

	public static CheckCsvResultParticipant.DataBuilder builder() {
		return new DataBuilderImpl();
	}
}
