// Generated by RSD - Do not modify
package at.mspe.server.rest.model;

import jakarta.json.JsonObject;

import at.mspe.server.service.model.CohortNew;

public abstract class CohortNewDataImpl implements CohortNew.Data {
	public static boolean isSupportedType(JsonObject obj) {
		var descriminator = obj.getString("@type");
		return switch (descriminator) {
			case "generic",
					"birthyear" ->
				true;
			default -> false;
		};
	}

	public static CohortNew.Data of(JsonObject obj) {
		var descriminator = obj.getString("@type");
		return switch (descriminator) {
			case "generic" -> new GenericCohortNewDataImpl(obj);
			case "birthyear" -> new BirthyearCohortNewDataImpl(obj);
			default -> throw new IllegalArgumentException("Unexpected value: %s".formatted(descriminator));
		};
	}
}
