// Generated by RSD - Do not modify
package at.mspe.server.rest.model;

import jakarta.json.JsonObject;

import at.mspe.server.service.model.Cohort;

public abstract class CohortDataImpl implements Cohort.Data {
	public static boolean isSupportedType(JsonObject obj) {
		var descriminator = obj.getString("@type");
		return switch (descriminator) {
			case "generic",
					"birthyear" ->
				true;
			default -> false;
		};
	}

	public static Cohort.Data of(JsonObject obj) {
		var descriminator = obj.getString("@type");
		return switch (descriminator) {
			case "generic" -> new GenericCohortDataImpl(obj);
			case "birthyear" -> new BirthyearCohortDataImpl(obj);
			default -> throw new IllegalArgumentException("Unexpected value: %s".formatted(descriminator));
		};
	}
}
