// Generated by RSD - Do not modify
package at.mspe.server.rest.model;

import jakarta.json.JsonObject;

import at.mspe.server.service.model.Cohort;

public abstract class CohortPatchImpl implements Cohort.Patch {
	public static boolean isSupportedType(JsonObject obj) {
		var descriminator = obj.getString("@type");
		return switch (descriminator) {
			case "patch:generic",
					"patch:birthyear" ->
				true;
			default -> false;
		};
	}

	public static Cohort.Patch of(JsonObject obj) {
		var descriminator = obj.getString("@type");
		return switch (descriminator) {
			case "patch:generic" -> new GenericCohortPatchImpl(obj);
			case "patch:birthyear" -> new BirthyearCohortPatchImpl(obj);
			default -> throw new IllegalArgumentException("Unexpected value: %s".formatted(descriminator));
		};
	}
}
