// Generated by RSD - Do not modify
package at.mspe.server.rest.model;

import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;

import at.mspe.server.service.model.Gender;
import at.mspe.server.service.model.GenericCohortNew;

public class GenericCohortNewDataImpl extends _BaseDataImpl implements GenericCohortNew.Data {
	GenericCohortNewDataImpl(JsonObject data) {
		super(data);
	}

	public String name() {
		return _JsonUtils.mapString(data, "name");
	}

	public Gender gender() {
		return _JsonUtils.mapLiteral(data, "gender", Gender::valueOf);
	}

	public static GenericCohortNew.Data of(JsonObject obj) {
		return new GenericCohortNewDataImpl(obj);
	}

	public String toString() {
		return getClass().getSimpleName();
	}

	public static class DataBuilderImpl implements GenericCohortNew.DataBuilder {
		private JsonObjectBuilder $builder = Json.createObjectBuilder();

		public DataBuilderImpl() {
			$builder.add("@type", "generic");
		}

		public GenericCohortNew.DataBuilder name(String name) {
			if (name == null) {
				return this;
			}
			$builder.add("name", name);
			return this;
		}

		public GenericCohortNew.DataBuilder gender(Gender gender) {
			if (gender == null) {
				return this;
			}
			$builder.add("gender", gender.toString());
			return this;
		}

		public GenericCohortNew.Data build() {
			return new GenericCohortNewDataImpl($builder.build());
		}
	}

	public static GenericCohortNew.DataBuilder builder() {
		return new DataBuilderImpl();
	}
}
