// Generated by RSD - Do not modify
package at.mspe.server.rest.model;

import java.util.Optional;

import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;

import at.mspe.server.service.model.Gender;
import at.mspe.server.service.model.GenericCohort;

public class GenericCohortPatchImpl extends _BaseDataImpl implements GenericCohort.Patch {
	GenericCohortPatchImpl(JsonObject data) {
		super(data);
	}

	public String key() {
		return _JsonUtils.mapString(data, "key");
	}

	public long version() {
		return _JsonUtils.mapLong(data, "version");
	}

	public Optional<String> name() {
		return _JsonUtils.mapOptString(data, "name");
	}

	public Optional<Gender> gender() {
		return _JsonUtils.mapOptLiteral(data, "gender", Gender::valueOf);
	}

	public static class PatchBuilderImpl implements GenericCohort.PatchBuilder {
		private JsonObjectBuilder $builder = Json.createObjectBuilder();

		public PatchBuilderImpl() {
			$builder.add("@type", "patch:generic");
		}

		public GenericCohort.PatchBuilder key(String key) {
			$builder.add("key", key);
			return this;
		}

		public GenericCohort.PatchBuilder version(long version) {
			$builder.add("version", version);
			return this;
		}

		@Override
		public GenericCohort.PatchBuilder name(String name) {
			$builder.add("name", name);
			return this;
		}

		@Override
		public GenericCohort.PatchBuilder gender(Gender gender) {
			;
			return this;
		}

		@Override
		public GenericCohort.Patch build() {
			return new GenericCohortPatchImpl($builder.build());
		}
	}

	public static GenericCohort.Patch of(JsonObject obj) {
		return new GenericCohortPatchImpl(obj);
	}

	public static PatchBuilderImpl builder() {
		return new PatchBuilderImpl();
	}
}
