// Generated by RSD - Do not modify
package at.mspe.server.rest.model;

import java.time.LocalDate;
import java.util.Optional;

import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;

import at.mspe.server.service.model._Base;
import at.mspe.server.service.model.Gender;
import at.mspe.server.service.model.Participant;

public class ParticipantPatchImpl extends _BaseDataImpl implements Participant.Patch {
	ParticipantPatchImpl(JsonObject data) {
		super(data);
	}

	public String key() {
		return _JsonUtils.mapString(data, "key");
	}

	public long version() {
		return _JsonUtils.mapLong(data, "version");
	}

	public _Base.Nillable<Long> time() {
		return _JsonUtils.mapNilLong(data, "time");
	}

	public Optional<String> firstname() {
		return _JsonUtils.mapOptString(data, "firstname");
	}

	public Optional<String> lastname() {
		return _JsonUtils.mapOptString(data, "lastname");
	}

	public _Base.Nillable<String> team() {
		return _JsonUtils.mapNilString(data, "team");
	}

	public _Base.Nillable<LocalDate> birthday() {
		return _JsonUtils.mapNilLocalDate(data, "birthday");
	}

	public Optional<Gender> gender() {
		return _JsonUtils.mapOptLiteral(data, "gender", Gender::valueOf);
	}

	public _Base.Nillable<String> association() {
		return _JsonUtils.mapNilString(data, "association");
	}

	public _Base.Nillable<String> cohortKey() {
		return _JsonUtils.mapNilString(data, "cohortKey");
	}

	public static class PatchBuilderImpl implements Participant.PatchBuilder {
		private JsonObjectBuilder $builder = Json.createObjectBuilder();

		public Participant.PatchBuilder key(String key) {
			$builder.add("key", key);
			return this;
		}

		public Participant.PatchBuilder version(long version) {
			$builder.add("version", version);
			return this;
		}

		@Override
		public Participant.PatchBuilder time(Long time) {
			if (time == null) {
				$builder.addNull("time");
				return this;
			}
			$builder.add("time", time);
			return this;
		}

		@Override
		public Participant.PatchBuilder firstname(String firstname) {
			$builder.add("firstname", firstname);
			return this;
		}

		@Override
		public Participant.PatchBuilder lastname(String lastname) {
			$builder.add("lastname", lastname);
			return this;
		}

		@Override
		public Participant.PatchBuilder team(String team) {
			if (team == null) {
				$builder.addNull("team");
				return this;
			}
			$builder.add("team", team);
			return this;
		}

		@Override
		public Participant.PatchBuilder birthday(LocalDate birthday) {
			if (birthday == null) {
				$builder.addNull("birthday");
				return this;
			}
			$builder.add("birthday", birthday.toString());
			return this;
		}

		@Override
		public Participant.PatchBuilder gender(Gender gender) {
			;
			return this;
		}

		@Override
		public Participant.PatchBuilder association(String association) {
			if (association == null) {
				$builder.addNull("association");
				return this;
			}
			$builder.add("association", association);
			return this;
		}

		@Override
		public Participant.PatchBuilder cohortKey(String cohortKey) {
			if (cohortKey == null) {
				$builder.addNull("cohortKey");
				return this;
			}
			$builder.add("cohortKey", cohortKey);
			return this;
		}

		@Override
		public Participant.Patch build() {
			return new ParticipantPatchImpl($builder.build());
		}
	}

	public static Participant.Patch of(JsonObject obj) {
		return new ParticipantPatchImpl(obj);
	}

	public static PatchBuilderImpl builder() {
		return new PatchBuilderImpl();
	}
}
