// Generated by RSD - Do not modify
package at.mspe.server.rest.model;

import java.time.ZonedDateTime;
import java.util.Optional;

import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;

import at.mspe.server.service.model.SportEvent;

public class SportEventPatchImpl extends _BaseDataImpl implements SportEvent.Patch {
	SportEventPatchImpl(JsonObject data) {
		super(data);
	}

	public String key() {
		return _JsonUtils.mapString(data, "key");
	}

	public long version() {
		return _JsonUtils.mapLong(data, "version");
	}

	public Optional<String> name() {
		return _JsonUtils.mapOptString(data, "name");
	}

	public Optional<ZonedDateTime> date() {
		return _JsonUtils.mapOptZonedDateTime(data, "date");
	}

	public static class PatchBuilderImpl implements SportEvent.PatchBuilder {
		private JsonObjectBuilder $builder = Json.createObjectBuilder();

		public SportEvent.PatchBuilder key(String key) {
			$builder.add("key", key);
			return this;
		}

		public SportEvent.PatchBuilder version(long version) {
			$builder.add("version", version);
			return this;
		}

		@Override
		public SportEvent.PatchBuilder name(String name) {
			$builder.add("name", name);
			return this;
		}

		@Override
		public SportEvent.PatchBuilder date(ZonedDateTime date) {
			$builder.add("date", date.toString());
			return this;
		}

		@Override
		public SportEvent.Patch build() {
			return new SportEventPatchImpl($builder.build());
		}
	}

	public static SportEvent.Patch of(JsonObject obj) {
		return new SportEventPatchImpl(obj);
	}

	public static PatchBuilderImpl builder() {
		return new PatchBuilderImpl();
	}
}
