// Generated by RSD - Do not modify
package at.mspe.server.rest.model;

import java.time.ZonedDateTime;

import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;

import at.mspe.server.service.model.SportEventNew;

public class SportEventNewDataImpl extends _BaseDataImpl implements SportEventNew.Data {
	SportEventNewDataImpl(JsonObject data) {
		super(data);
	}

	@Override
	public String name() {
		return _JsonUtils.mapString(data, "name");
	}

	@Override
	public ZonedDateTime date() {
		return _JsonUtils.mapZonedDateTime(data, "date");
	}

	@Override
	public String registrationUrl() {
		return _JsonUtils.mapString(data, "registrationUrl", null);
	}

	public static SportEventNew.Data of(JsonObject obj) {
		return new SportEventNewDataImpl(obj);
	}

	public String toString() {
		return getClass().getSimpleName();
	}

	public static class DataBuilderImpl implements SportEventNew.DataBuilder {
		private JsonObjectBuilder $builder = Json.createObjectBuilder();

		@Override
		public SportEventNew.DataBuilder name(String name) {
			if (name == null) {
				return this;
			}
			$builder.add("name", name);
			return this;
		}

		@Override
		public SportEventNew.DataBuilder date(ZonedDateTime date) {
			if (date == null) {
				return this;
			}
			$builder.add("date", date.toString());
			return this;
		}

		@Override
		public SportEventNew.DataBuilder registrationUrl(String registrationUrl) {
			if (registrationUrl == null) {
				return this;
			}
			$builder.add("registrationUrl", registrationUrl);
			return this;
		}

		public SportEventNew.Data build() {
			return new SportEventNewDataImpl($builder.build());
		}
	}

	public static SportEventNew.DataBuilder builder() {
		return new DataBuilderImpl();
	}
}
