// Generated by RSD - Do not modify
package at.mspe.server.rest.model;

import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;

import at.mspe.server.service.model.UpdateResult;

public class UpdateResultDataImpl extends _BaseDataImpl implements UpdateResult.Data {
	UpdateResultDataImpl(JsonObject data) {
		super(data);
	}

	public String key() {
		return _JsonUtils.mapString(data, "key");
	}

	public long version() {
		return _JsonUtils.mapLong(data, "version");
	}

	public static UpdateResult.Data of(JsonObject obj) {
		return new UpdateResultDataImpl(obj);
	}

	public String toString() {
		return getClass().getSimpleName();
	}

	public static class DataBuilderImpl implements UpdateResult.DataBuilder {
		private JsonObjectBuilder $builder = Json.createObjectBuilder();

		public UpdateResult.DataBuilder key(String key) {
			if (key == null) {
				return this;
			}
			$builder.add("key", key);
			return this;
		}

		public UpdateResult.DataBuilder version(long version) {
			$builder.add("version", version);
			return this;
		}

		public UpdateResult.Data build() {
			return new UpdateResultDataImpl($builder.build());
		}
	}

	public static UpdateResult.DataBuilder builder() {
		return new DataBuilderImpl();
	}
}
