// Generated by RSD - Do not modify
package at.mspe.server.rest;

import java.util.List;

import jakarta.inject.Singleton;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.core.Response.ResponseBuilder;

import at.mspe.server.rest.model._JsonUtils;
import at.mspe.server.service.model.Cohort;
import at.mspe.server.service.model.CohortNew;
import at.mspe.server.service.model.UpdateResult;

@Singleton
public class EventCohortResourceResponseBuilder {
	public ResponseBuilder get(Cohort.Data $result, String eventKey, String key) {
		return Response.status(200).entity(_JsonUtils.toJsonString($result, false));
	}

	public ResponseBuilder list(List<Cohort.Data> $result, String eventKey) {
		return Response.status(200).entity(_JsonUtils.toJsonString($result, false));
	}

	public ResponseBuilder create(String $result, String eventKey, CohortNew.Data cohort) {
		return Response.status(201).entity(_JsonUtils.encodeAsJsonString($result));
	}

	public ResponseBuilder update(UpdateResult.Data $result, String eventKey, String key, Cohort.Patch cohort) {
		return Response.status(200).entity(_JsonUtils.toJsonString($result, false));
	}

	public ResponseBuilder delete(String eventKey, String key, Long version) {
		return Response.status(200);
	}

}
