// Generated by RSD - Do not modify
package at.mspe.server.rest;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.HeaderParam;
import jakarta.ws.rs.PATCH;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Produces;

import at.mspe.server.service.EventCohortService;
import at.mspe.server.service.InvalidDataException;
import at.mspe.server.service.model.Cohort;
import at.mspe.server.service.model.CohortNew;
import at.mspe.server.service.NotFoundException;
import at.mspe.server.service.StaleDataException;

@ApplicationScoped
@Path("/api/sportevent/{eventKey}/cohorts")
@Produces(MediaType.APPLICATION_JSON)
public class EventCohortResource {
	private final RestBuilderFactory builderFactory;
	private final EventCohortService service;
	private final EventCohortResourceResponseBuilder responseBuilder;

	@Inject
	public EventCohortResource(EventCohortService service, EventCohortResourceResponseBuilder responseBuilder, RestBuilderFactory builderFactory) {
		this.builderFactory = builderFactory;
		this.service = service;
		this.responseBuilder = responseBuilder;
	}

	@GET
	@Path("{key}")
	public Response get(
			@PathParam("eventKey") String _eventKey,
			@PathParam("key") String _key) {
		var eventKey = _eventKey;
		var key = _key;
		try {
			var result = service.get(builderFactory, eventKey, key);
			return responseBuilder.get(result, eventKey, key).build();
		} catch (NotFoundException e) {
			return _RestUtils.toResponse(404, e);
		}
	}

	@GET
	public Response list(@PathParam("eventKey") String _eventKey) {
		var eventKey = _eventKey;
		try {
			var result = service.list(builderFactory, eventKey);
			return responseBuilder.list(result, eventKey).build();
		} catch (NotFoundException e) {
			return _RestUtils.toResponse(404, e);
		}
	}

	@POST
	public Response create(
			@PathParam("eventKey") String _eventKey,
			String _cohort) {
		var eventKey = _eventKey;
		var cohort = builderFactory.of(CohortNew.Data.class, _cohort);
		try {
			var result = service.create(builderFactory, eventKey, cohort);
			return responseBuilder.create(result, eventKey, cohort).build();
		} catch (NotFoundException e) {
			return _RestUtils.toResponse(404, e);
		} catch (InvalidDataException e) {
			return _RestUtils.toResponse(422, e);
		}
	}

	@PATCH
	@Path("{key}")
	public Response update(
			@PathParam("eventKey") String _eventKey,
			@PathParam("key") String _key,
			String _cohort) {
		var eventKey = _eventKey;
		var key = _key;
		var cohort = builderFactory.of(Cohort.Patch.class, _cohort);
		try {
			var result = service.update(builderFactory, eventKey, key, cohort);
			return responseBuilder.update(result, eventKey, key, cohort).build();
		} catch (NotFoundException e) {
			return _RestUtils.toResponse(404, e);
		} catch (InvalidDataException e) {
			return _RestUtils.toResponse(422, e);
		} catch (StaleDataException e) {
			return _RestUtils.toResponse(412, e);
		}
	}

	@DELETE
	@Path("{key}")
	public Response delete(
			@PathParam("eventKey") String _eventKey,
			@PathParam("key") String _key,
			@HeaderParam("version") Long _version) {
		var eventKey = _eventKey;
		var key = _key;
		var version = _version;
		try {
			service.delete(builderFactory, eventKey, key, version);
			return responseBuilder.delete(eventKey, key, version).build();
		} catch (NotFoundException e) {
			return _RestUtils.toResponse(404, e);
		} catch (StaleDataException e) {
			return _RestUtils.toResponse(412, e);
		}
	}

}
