// Generated by RSD - Do not modify
package at.mspe.server.rest;

import java.util.List;

import jakarta.inject.Singleton;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.core.Response.ResponseBuilder;

import at.mspe.server.rest.model._JsonUtils;
import at.mspe.server.service.model.Participant;
import at.mspe.server.service.model.ParticipantNew;

@Singleton
public class EventParticipantResourceResponseBuilder {
	public ResponseBuilder get(Participant.Data $result, String eventKey) {
		return Response.status(200).entity(_JsonUtils.toJsonString($result, false));
	}

	public ResponseBuilder list(List<Participant.Data> $result, String eventKey) {
		return Response.status(200).entity(_JsonUtils.toJsonString($result, false));
	}

	public ResponseBuilder create(String $result, String eventKey, ParticipantNew.Data participant) {
		return Response.status(201).entity(_JsonUtils.encodeAsJsonString($result));
	}

	public ResponseBuilder update(String eventKey, String key, Participant.Patch participant) {
		return Response.status(200);
	}

	public ResponseBuilder delete(String eventKey, String key) {
		return Response.status(200);
	}

}
