// Generated by RSD - Do not modify
package at.mspe.server.rest;

import java.io.InputStream;
import java.nio.file.Path;
import java.util.List;

import jakarta.inject.Singleton;
import jakarta.json.JsonArray;
import jakarta.json.JsonObject;

import at.mspe.server.rest.model._BlobImpl;
import at.mspe.server.rest.model._FileImpl;
import at.mspe.server.rest.model._JsonUtils;
import at.mspe.server.rest.model._StreamBlobImpl;
import at.mspe.server.rest.model.BirthyearCohortDataImpl;
import at.mspe.server.rest.model.BirthyearCohortNewDataImpl;
import at.mspe.server.rest.model.BirthyearCohortPatchImpl;
import at.mspe.server.rest.model.CheckCsvResultDataImpl;
import at.mspe.server.rest.model.CheckCsvResultParticipantDataImpl;
import at.mspe.server.rest.model.CohortDataImpl;
import at.mspe.server.rest.model.CohortNewDataImpl;
import at.mspe.server.rest.model.CohortPatchImpl;
import at.mspe.server.rest.model.GenericCohortDataImpl;
import at.mspe.server.rest.model.GenericCohortNewDataImpl;
import at.mspe.server.rest.model.GenericCohortPatchImpl;
import at.mspe.server.rest.model.ParticipantDataImpl;
import at.mspe.server.rest.model.ParticipantNewDataImpl;
import at.mspe.server.rest.model.ParticipantPatchImpl;
import at.mspe.server.rest.model.SportEventDataImpl;
import at.mspe.server.rest.model.SportEventNewDataImpl;
import at.mspe.server.rest.model.SportEventPatchImpl;
import at.mspe.server.rest.model.UpdateResultDataImpl;
import at.mspe.server.service.BuilderFactory;
import at.mspe.server.service.model._Base;
import at.mspe.server.service.model.BirthyearCohort;
import at.mspe.server.service.model.BirthyearCohortNew;
import at.mspe.server.service.model.CheckCsvResult;
import at.mspe.server.service.model.CheckCsvResultParticipant;
import at.mspe.server.service.model.Cohort;
import at.mspe.server.service.model.CohortNew;
import at.mspe.server.service.model.GenericCohort;
import at.mspe.server.service.model.GenericCohortNew;
import at.mspe.server.service.model.Participant;
import at.mspe.server.service.model.ParticipantNew;
import at.mspe.server.service.model.RSDBlob;
import at.mspe.server.service.model.RSDFile;
import at.mspe.server.service.model.SportEvent;
import at.mspe.server.service.model.SportEventNew;
import at.mspe.server.service.model.UpdateResult;

@Singleton
public class RestBuilderFactory implements BuilderFactory {
	@Override
	public <T extends _Base.BaseDataBuilder<?>> T builder(Class<T> type) {
		if (type == GenericCohortNew.DataBuilder.class) {
			return type.cast(GenericCohortNewDataImpl.builder());
		}
		if (type == BirthyearCohortNew.DataBuilder.class) {
			return type.cast(BirthyearCohortNewDataImpl.builder());
		}
		if (type == GenericCohort.DataBuilder.class) {
			return type.cast(GenericCohortDataImpl.builder());
		}
		if (type == GenericCohort.PatchBuilder.class) {
			return type.cast(GenericCohortPatchImpl.builder());
		}
		if (type == BirthyearCohort.DataBuilder.class) {
			return type.cast(BirthyearCohortDataImpl.builder());
		}
		if (type == BirthyearCohort.PatchBuilder.class) {
			return type.cast(BirthyearCohortPatchImpl.builder());
		}
		if (type == SportEventNew.DataBuilder.class) {
			return type.cast(SportEventNewDataImpl.builder());
		}
		if (type == SportEvent.DataBuilder.class) {
			return type.cast(SportEventDataImpl.builder());
		}
		if (type == SportEvent.PatchBuilder.class) {
			return type.cast(SportEventPatchImpl.builder());
		}
		if (type == ParticipantNew.DataBuilder.class) {
			return type.cast(ParticipantNewDataImpl.builder());
		}
		if (type == Participant.DataBuilder.class) {
			return type.cast(ParticipantDataImpl.builder());
		}
		if (type == Participant.PatchBuilder.class) {
			return type.cast(ParticipantPatchImpl.builder());
		}
		if (type == UpdateResult.DataBuilder.class) {
			return type.cast(UpdateResultDataImpl.builder());
		}
		if (type == CheckCsvResultParticipant.DataBuilder.class) {
			return type.cast(CheckCsvResultParticipantDataImpl.builder());
		}
		if (type == CheckCsvResult.DataBuilder.class) {
			return type.cast(CheckCsvResultDataImpl.builder());
		}
		throw new IllegalArgumentException("Unsupported Builder '%s'".formatted(type));
	}

	public <T extends _Base.BaseData> T of(Class<T> type, JsonObject data) {
		if (type == GenericCohortNew.Data.class) {
			return type.cast(GenericCohortNewDataImpl.of(data));
		}
		if (type == BirthyearCohortNew.Data.class) {
			return type.cast(BirthyearCohortNewDataImpl.of(data));
		}
		if (type == GenericCohort.Data.class) {
			return type.cast(GenericCohortDataImpl.of(data));
		}
		if (type == GenericCohort.Patch.class) {
			return type.cast(GenericCohortPatchImpl.of(data));
		}
		if (type == BirthyearCohort.Data.class) {
			return type.cast(BirthyearCohortDataImpl.of(data));
		}
		if (type == BirthyearCohort.Patch.class) {
			return type.cast(BirthyearCohortPatchImpl.of(data));
		}
		if (type == SportEventNew.Data.class) {
			return type.cast(SportEventNewDataImpl.of(data));
		}
		if (type == SportEvent.Data.class) {
			return type.cast(SportEventDataImpl.of(data));
		}
		if (type == SportEvent.Patch.class) {
			return type.cast(SportEventPatchImpl.of(data));
		}
		if (type == ParticipantNew.Data.class) {
			return type.cast(ParticipantNewDataImpl.of(data));
		}
		if (type == Participant.Data.class) {
			return type.cast(ParticipantDataImpl.of(data));
		}
		if (type == Participant.Patch.class) {
			return type.cast(ParticipantPatchImpl.of(data));
		}
		if (type == UpdateResult.Data.class) {
			return type.cast(UpdateResultDataImpl.of(data));
		}
		if (type == CheckCsvResultParticipant.Data.class) {
			return type.cast(CheckCsvResultParticipantDataImpl.of(data));
		}
		if (type == CheckCsvResult.Data.class) {
			return type.cast(CheckCsvResultDataImpl.of(data));
		}
		if (type == CohortNew.Data.class) {
			return type.cast(CohortNewDataImpl.of(data));
		}
		if (type == Cohort.Data.class) {
			return type.cast(CohortDataImpl.of(data));
		}
		if (type == Cohort.Patch.class) {
			return type.cast(CohortPatchImpl.of(data));
		}

		throw new IllegalArgumentException("Unsupported Builder '%s'".formatted(type));
	}

	@SuppressWarnings("unchecked")
	public <T extends _Base.BaseData> List<T> of(Class<T> type, JsonArray data) {
		if (type == GenericCohortNew.Data.class) {
			return (List<T>) _JsonUtils.mapObjects(data,  GenericCohortNewDataImpl::of);
		}
		if (type == BirthyearCohortNew.Data.class) {
			return (List<T>) _JsonUtils.mapObjects(data,  BirthyearCohortNewDataImpl::of);
		}
		if (type == GenericCohort.Data.class) {
			return (List<T>) _JsonUtils.mapObjects(data,  GenericCohortDataImpl::of);
		}
		if (type == GenericCohort.Patch.class) {
			return (List<T>) _JsonUtils.mapObjects(data,  GenericCohortPatchImpl::of);
		}
		if (type == BirthyearCohort.Data.class) {
			return (List<T>) _JsonUtils.mapObjects(data,  BirthyearCohortDataImpl::of);
		}
		if (type == BirthyearCohort.Patch.class) {
			return (List<T>) _JsonUtils.mapObjects(data,  BirthyearCohortPatchImpl::of);
		}
		if (type == SportEventNew.Data.class) {
			return (List<T>) _JsonUtils.mapObjects(data,  SportEventNewDataImpl::of);
		}
		if (type == SportEvent.Data.class) {
			return (List<T>) _JsonUtils.mapObjects(data,  SportEventDataImpl::of);
		}
		if (type == SportEvent.Patch.class) {
			return (List<T>) _JsonUtils.mapObjects(data,  SportEventPatchImpl::of);
		}
		if (type == ParticipantNew.Data.class) {
			return (List<T>) _JsonUtils.mapObjects(data,  ParticipantNewDataImpl::of);
		}
		if (type == Participant.Data.class) {
			return (List<T>) _JsonUtils.mapObjects(data,  ParticipantDataImpl::of);
		}
		if (type == Participant.Patch.class) {
			return (List<T>) _JsonUtils.mapObjects(data,  ParticipantPatchImpl::of);
		}
		if (type == UpdateResult.Data.class) {
			return (List<T>) _JsonUtils.mapObjects(data,  UpdateResultDataImpl::of);
		}
		if (type == CheckCsvResultParticipant.Data.class) {
			return (List<T>) _JsonUtils.mapObjects(data,  CheckCsvResultParticipantDataImpl::of);
		}
		if (type == CheckCsvResult.Data.class) {
			return (List<T>) _JsonUtils.mapObjects(data,  CheckCsvResultDataImpl::of);
		}
		if (type == CohortNew.Data.class) {
			return (List<T>) _JsonUtils.mapObjects(data,  CohortNewDataImpl::of);
		}
		if (type == Cohort.Data.class) {
			return (List<T>) _JsonUtils.mapObjects(data,  CohortDataImpl::of);
		}
		if (type == Cohort.Patch.class) {
			return (List<T>) _JsonUtils.mapObjects(data,  CohortPatchImpl::of);
		}

		throw new IllegalArgumentException("Unsupported Builder '%s'".formatted(type));
	}

	public RSDBlob createBlob(Path file, String mimeType) {
		return _BlobImpl.of(file, mimeType);
	}

	public RSDBlob createBlob(InputStream stream, String mimeType) {
		return _StreamBlobImpl.of(stream, mimeType);
	}

	public RSDFile createFile(Path file, String mimeType, String filename) {
		return _FileImpl.of(file, mimeType, filename);
	}
}
