// Generated by RSD - Do not modify
package at.mspe.server.rest;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.PATCH;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Produces;

import at.mspe.server.service.InvalidDataException;
import at.mspe.server.service.model.Participant;
import at.mspe.server.service.model.SportEventNew;
import at.mspe.server.service.NotFoundException;
import at.mspe.server.service.SportEventService;

@ApplicationScoped
@Path("/api/sportevent")
@Produces(MediaType.APPLICATION_JSON)
public class SportEventResource {
	private final RestBuilderFactory builderFactory;
	private final SportEventService service;
	private final SportEventResourceResponseBuilder responseBuilder;

	@Inject
	public SportEventResource(SportEventService service, SportEventResourceResponseBuilder responseBuilder, RestBuilderFactory builderFactory) {
		this.builderFactory = builderFactory;
		this.service = service;
		this.responseBuilder = responseBuilder;
	}

	@GET
	@Path("{key}")
	public Response get(@PathParam("key") String _key) {
		var key = _key;
		try {
			var result = service.get(builderFactory, key);
			return responseBuilder.get(result, key).build();
		} catch (NotFoundException e) {
			return _RestUtils.toResponse(404, e);
		}
	}

	@GET
	public Response list() {
		var result = service.list(builderFactory);
		return responseBuilder.list(result).build();
	}

	@POST
	public Response create(String _participant) {
		var participant = builderFactory.of(SportEventNew.Data.class, _participant);
		try {
			var result = service.create(builderFactory, participant);
			return responseBuilder.create(result, participant).build();
		} catch (InvalidDataException e) {
			return _RestUtils.toResponse(422, e);
		}
	}

	@PATCH
	@Path("{key}")
	public Response update(
			@PathParam("key") String _key,
			String _participant) {
		var key = _key;
		var participant = builderFactory.of(Participant.Patch.class, _participant);
		try {
			service.update(builderFactory, key, participant);
			return responseBuilder.update(key, participant).build();
		} catch (NotFoundException e) {
			return _RestUtils.toResponse(404, e);
		} catch (InvalidDataException e) {
			return _RestUtils.toResponse(422, e);
		}
	}

	@DELETE
	@Path("{key}")
	public Response delete(@PathParam("key") String _key) {
		var key = _key;
		try {
			service.delete(builderFactory, key);
			return responseBuilder.delete(key).build();
		} catch (NotFoundException e) {
			return _RestUtils.toResponse(404, e);
		} catch (InvalidDataException e) {
			return _RestUtils.toResponse(422, e);
		}
	}

}
