// Generated by RSD - Do not modify
package at.mspe.server.rest;

import java.util.List;

import jakarta.inject.Singleton;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.core.Response.ResponseBuilder;

import at.mspe.server.rest.model._JsonUtils;
import at.mspe.server.service.model.SportEvent;
import at.mspe.server.service.model.SportEventNew;
import at.mspe.server.service.model.UpdateResult;

@Singleton
public class SportEventResourceResponseBuilder {
	public ResponseBuilder get(SportEvent.Data $result, String key) {
		return Response.status(200).entity(_JsonUtils.toJsonString($result, false));
	}

	public ResponseBuilder list(List<SportEvent.Data> $result) {
		return Response.status(200).entity(_JsonUtils.toJsonString($result, false));
	}

	public ResponseBuilder create(String $result, SportEventNew.Data event) {
		return Response.status(201).entity(_JsonUtils.encodeAsJsonString($result));
	}

	public ResponseBuilder update(UpdateResult.Data $result, String key, SportEvent.Patch event) {
		return Response.status(200).entity(_JsonUtils.toJsonString($result, false));
	}

	public ResponseBuilder delete(String key, Long version) {
		return Response.status(200);
	}

}
